import Foundation

// Zusätzliche Overlays für den watchOS-Recorder (WLoc) — pt/ja/zh/ru/id.
// Eigene Datei (wie LocExtra.swift auf iOS). Fallback je Key: Englisch (siehe WLoc.t).

// Portugiesisch-Overlay (71 Keys). Fallback: Englisch.
let wPtOverlay: [String: String] = [
    "rec.paused": "Pausado",
    "rec.keepOpen": "mantenha o app aberto!",
    "rec.locPerm": "Localização não permitida – não é possível gravar",
    "rec.locCoarse": "Localização apenas aproximada – permita “Precisa”",
    "pair.title": "Conectar relógio",
    "pair.howto": "Gere um código de pareamento e digite-o no pumpfoil.org (Conta).",
    "pair.gen": "Gerar código de pareamento",
    "pair.enterOn": "Digite no pumpfoil.org:",
    "pair.waiting": "aguardando confirmação…",
    "pair.later": "Conectar depois",
    "rec.start": "Iniciar",
    "rec.stop": "Parar",
    "rec.stopHold": "Parar · segure 2 s",
    "rec.starting": "iniciando…",
    "rec.autoStart": "Auto-início ligado",
    "rec.autoStartToggle": "Auto-início",
    "rec.autoStartHelp": "Inicia sozinho a 10 km/h – caso você esqueça.",
    "rec.recording": "Gravando",
    "rec.saving": "salvando…",
    "rec.saved": "salvo",
    "rec.workoutFail": "Falha ao iniciar o treino: ",
    "rec.sync": "Sincr.…",
    "rec.notNow": "Agora não",
    "rec.toData": "Campos de dados →",
    "rec.toSummary": "← Resumo",
    "rec.notLinked": "Não vinculado – sessões locais",
    "rec.connect": "Conectar",
    "rec.pendingUpload": "aguardando envio",
    "rec.uploadNow": "Enviar agora",
    "rec.waitConn": "aguardando conexão",
    "rec.willResume": "vai retomar",
    "rec.uploading": "enviando",
    "rec.serverErr": "Erro no servidor – tente depois",
    "rec.authErr": "Vínculo inválido – reconecte",
    "rec.repair": "Reconectar",
    "rec.switch": "Trocar de conta",
    "rec.alarm": "Alarme",
    "rec.change": "alterar",
    "rec.holdProgress": "segure…",
    "foil.choose": "Escolher foil",
    "foil.chooseHelp": "Salva seu foil nesta sessão e define os limites do alarme quando a fonte está em Foil.",
    "foil.prefix": "Foil: ",
    "foil.alarm": "Alarme",
    "foil.alarmOn": "Alarme por vibração",
    "foil.alarmHelp": "Vibra quando você passa acima ou abaixo da faixa de velocidade ideal do seu foil.",
    "foil.thresholds": "Limites",
    "foil.source": "Fonte",
    "foil.auto": "Auto (foil)",
    "foil.manual": "Manual",
    "foil.min": "Mín.",
    "foil.max": "Máx.",
    "foil.noFoil": "Sem foil",
    "foil.fixed": "Valores fixos",
    "foil.none": "Sem foil",
    "foil.noneSub": "sem alarme",
    "foil.trigger": "Disparo",
    "foil.continuous": "Contínuo",
    "common.cancel": "Cancelar",
    "f.kmh3s": "km/h (3s)",
    "f.kmh": "km/h",
    "f.kmhAvg": "km/h méd.",
    "f.kmhMax": "km/h máx.",
    "f.bpm": "bpm",
    "f.bpmAvg": "bpm méd.",
    "f.bpmMax": "bpm máx.",
    "f.time": "Tempo",
    "f.clock": "Relógio",
    "f.alt": "Altitude",
    "f.temp": "Temp.",
    "f.ascent": "Subida",
    "f.runTime": "Tempo run",
    "f.runDist": "Dist. run",
    "f.runs": "Runs",
    "f.lastRunTime": "últ. tempo",
    "f.lastRunDist": "últ. dist.",
    "f.lastRunAvg": "últ. méd.",
    "f.lastRunMax": "últ. máx.",
]

// Japanisch-Overlay (71 Keys). Fallback: Englisch.
let wJaOverlay: [String: String] = [
    "rec.keepOpen": "アプリを開いたままに",
    "rec.locPerm": "位置情報が許可されていません – 記録できません",
    "rec.locCoarse": "おおよその位置のみ – 「正確な位置」を許可",
    "pair.title": "ウォッチを接続",
    "pair.howto": "ペアリングコードを生成し、pumpfoil.org(アカウント)で入力します。",
    "pair.gen": "ペアリングコードを生成",
    "pair.enterOn": "pumpfoil.orgで入力:",
    "pair.waiting": "確認待ち…",
    "pair.later": "後で接続",
    "rec.start": "スタート",
    "rec.stop": "ストップ",
    "rec.stopHold": "停止 · 2秒長押し",
    "rec.starting": "開始中…",
    "rec.autoStart": "自動スタート オン",
    "rec.autoStartToggle": "自動スタート",
    "rec.autoStartHelp": "10 km/hで自動スタート—忘れても安心。",
    "rec.recording": "記録中",
    "rec.saving": "保存中…",
    "rec.saved": "保存しました",
    "rec.workoutFail": "ワークアウト開始失敗: ",
    "rec.sync": "同期…",
    "rec.notNow": "後で",
    "rec.toData": "データ画面 →",
    "rec.toSummary": "← サマリー",
    "rec.notLinked": "未連携 – セッションはローカル",
    "rec.connect": "接続",
    "rec.pendingUpload": "アップロード待ち",
    "rec.uploadNow": "今すぐアップロード",
    "rec.waitConn": "接続待ち",
    "rec.willResume": "再開します",
    "rec.uploading": "アップロード中",
    "rec.serverErr": "サーバーエラー – 後で再試行",
    "rec.authErr": "連携が無効 – 再接続",
    "rec.repair": "再接続",
    "rec.switch": "アカウント切替",
    "rec.alarm": "アラーム",
    "rec.change": "変更",
    "rec.holdProgress": "長押し…",
    "foil.choose": "フォイルを選択",
    "foil.chooseHelp": "フォイルをこのセッションに保存し、ソースがフォイルの場合はアラームのしきい値を設定します。",
    "foil.prefix": "フォイル: ",
    "foil.alarm": "アラーム",
    "foil.alarmOn": "バイブアラーム",
    "foil.alarmHelp": "フォイルの最適速度域を上回る・下回ると振動します。",
    "foil.thresholds": "しきい値",
    "foil.source": "ソース",
    "foil.auto": "自動(フォイル)",
    "foil.manual": "手動",
    "foil.min": "最小",
    "foil.max": "最大",
    "foil.noFoil": "フォイルなし",
    "foil.fixed": "固定値",
    "foil.none": "フォイルなし",
    "foil.noneSub": "アラームなし",
    "foil.trigger": "トリガー",
    "foil.continuous": "連続",
    "common.cancel": "キャンセル",
    "f.kmh3s": "km/h(3秒)",
    "f.kmh": "km/h",
    "f.kmhAvg": "平均 km/h",
    "f.kmhMax": "最高 km/h",
    "f.bpm": "bpm",
    "f.bpmAvg": "平均 bpm",
    "f.bpmMax": "最高 bpm",
    "f.time": "時間",
    "f.clock": "時計",
    "f.alt": "高度",
    "f.temp": "気温",
    "f.ascent": "上昇",
    "f.runTime": "ラン時間",
    "f.runDist": "ラン距離",
    "f.runs": "ラン",
    "f.lastRunTime": "前回時間",
    "f.lastRunDist": "前回距離",
    "f.lastRunAvg": "前回平均",
    "f.lastRunMax": "前回最高",
]

// Chinesisch (vereinfacht)-Overlay (71 Keys). Fallback: Englisch.
let wZhOverlay: [String: String] = [
    "rec.keepOpen": "请保持应用打开",
    "rec.locPerm": "未允许位置权限 – 无法记录",
    "rec.locCoarse": "仅大致位置 – 请允许「精确位置」",
    "pair.title": "连接手表",
    "pair.howto": "生成配对码，在 pumpfoil.org（账户）中输入。",
    "pair.gen": "生成配对码",
    "pair.enterOn": "在 pumpfoil.org 输入：",
    "pair.waiting": "等待确认…",
    "pair.later": "稍后连接",
    "rec.start": "开始",
    "rec.stop": "停止",
    "rec.stopHold": "停止 · 长按 2 s",
    "rec.starting": "启动中…",
    "rec.autoStart": "自动开始：开",
    "rec.autoStartToggle": "自动开始",
    "rec.autoStartHelp": "10 km/h 时自动开始 — 以防你忘记。",
    "rec.recording": "记录中",
    "rec.saving": "保存中…",
    "rec.saved": "已保存",
    "rec.workoutFail": "训练启动失败： ",
    "rec.sync": "同步…",
    "rec.notNow": "暂不",
    "rec.toData": "数据字段 →",
    "rec.toSummary": "← 摘要",
    "rec.notLinked": "未连接 — 记录仅在本地",
    "rec.connect": "连接",
    "rec.pendingUpload": "待上传",
    "rec.uploadNow": "立即上传",
    "rec.waitConn": "等待连接",
    "rec.willResume": "将恢复",
    "rec.uploading": "上传中",
    "rec.serverErr": "服务器错误 — 稍后重试",
    "rec.authErr": "连接失效 — 请重连",
    "rec.repair": "重新连接",
    "rec.switch": "切换账户",
    "rec.alarm": "提醒",
    "rec.change": "更改",
    "rec.holdProgress": "长按…",
    "foil.choose": "选择 foil",
    "foil.chooseHelp": "将 foil 保存到本次记录，并在来源设为 Foil 时设定提醒阈值。",
    "foil.prefix": "Foil： ",
    "foil.alarm": "提醒",
    "foil.alarmOn": "震动提醒",
    "foil.alarmHelp": "当你高于或低于 foil 最佳速度区间时震动。",
    "foil.thresholds": "阈值",
    "foil.source": "来源",
    "foil.auto": "自动（foil）",
    "foil.manual": "手动",
    "foil.min": "最低",
    "foil.max": "最高",
    "foil.noFoil": "无 foil",
    "foil.fixed": "固定值",
    "foil.none": "无 foil",
    "foil.noneSub": "无提醒",
    "foil.trigger": "触发",
    "foil.continuous": "持续",
    "common.cancel": "取消",
    "f.kmh3s": "km/h（3秒）",
    "f.kmh": "km/h",
    "f.kmhAvg": "平均 km/h",
    "f.kmhMax": "最高 km/h",
    "f.bpm": "bpm",
    "f.bpmAvg": "平均 bpm",
    "f.bpmMax": "最高 bpm",
    "f.time": "时间",
    "f.clock": "时钟",
    "f.alt": "海拔",
    "f.temp": "温度",
    "f.ascent": "爬升",
    "f.runTime": "航次时长",
    "f.runDist": "航次距离",
    "f.runs": "航次",
    "f.lastRunTime": "上次时长",
    "f.lastRunDist": "上次距离",
    "f.lastRunAvg": "上次平均",
    "f.lastRunMax": "上次最高",
]

// Russisch-Overlay (71 Keys). Fallback: Englisch.
let wRuOverlay: [String: String] = [
    "rec.paused": "Пауза",
    "rec.keepOpen": "не закрывайте приложение!",
    "rec.locPerm": "Геолокация запрещена – запись невозможна",
    "rec.locCoarse": "Только приблизительная геопозиция – разрешите «Точную»",
    "pair.title": "Подключить часы",
    "pair.howto": "Сгенерируйте код сопряжения и введите его на pumpfoil.org (Аккаунт).",
    "pair.gen": "Сгенерировать код",
    "pair.enterOn": "Введите на pumpfoil.org:",
    "pair.waiting": "ждём подтверждения…",
    "pair.later": "Позже",
    "rec.start": "Старт",
    "rec.stop": "Стоп",
    "rec.stopHold": "Стоп · держите 2 с",
    "rec.starting": "запуск…",
    "rec.autoStart": "Автостарт вкл",
    "rec.autoStartToggle": "Автостарт",
    "rec.autoStartHelp": "Автостарт при 10 км/ч — если забудете.",
    "rec.recording": "Запись",
    "rec.saving": "сохранение…",
    "rec.saved": "сохранено",
    "rec.workoutFail": "Ошибка запуска тренировки: ",
    "rec.sync": "Синхр…",
    "rec.notNow": "Не сейчас",
    "rec.toData": "Поля данных →",
    "rec.toSummary": "← Итоги",
    "rec.notLinked": "Не привязано — локально",
    "rec.connect": "Подключить",
    "rec.pendingUpload": "ждёт загрузки",
    "rec.uploadNow": "Загрузить",
    "rec.waitConn": "ждём связь",
    "rec.willResume": "продолжится",
    "rec.uploading": "загрузка",
    "rec.serverErr": "Ошибка сервера — позже",
    "rec.authErr": "Привязка недействительна — заново",
    "rec.repair": "Переподключить",
    "rec.switch": "Сменить аккаунт",
    "rec.alarm": "Сигнал",
    "rec.change": "изменить",
    "rec.holdProgress": "держите…",
    "foil.choose": "Выбрать foil",
    "foil.chooseHelp": "Сохраняет foil для этой сессии и задаёт пороги сигнала, когда источник — Foil.",
    "foil.prefix": "Foil: ",
    "foil.alarm": "Сигнал",
    "foil.alarmOn": "Виброзвонок",
    "foil.alarmHelp": "Вибрирует, когда вы выходите за оптимальный диапазон скорости foil.",
    "foil.thresholds": "Пороги",
    "foil.source": "Источник",
    "foil.auto": "Авто (foil)",
    "foil.manual": "Вручную",
    "foil.min": "Мин",
    "foil.max": "Макс",
    "foil.noFoil": "Без foil",
    "foil.fixed": "Фикс. значения",
    "foil.none": "Без foil",
    "foil.noneSub": "без сигнала",
    "foil.trigger": "Триггер",
    "foil.continuous": "Постоянно",
    "common.cancel": "Отмена",
    "f.kmh3s": "км/ч (3с)",
    "f.kmh": "км/ч",
    "f.kmhAvg": "Ø км/ч",
    "f.kmhMax": "макс км/ч",
    "f.bpm": "уд/мин",
    "f.bpmAvg": "Ø уд/мин",
    "f.bpmMax": "макс уд/мин",
    "f.time": "Время",
    "f.clock": "Часы",
    "f.alt": "Высота",
    "f.temp": "Темп",
    "f.ascent": "Набор",
    "f.runTime": "Время заезда",
    "f.runDist": "Дист. заезда",
    "f.runs": "Заезды",
    "f.lastRunTime": "посл. время",
    "f.lastRunDist": "посл. дист.",
    "f.lastRunAvg": "посл. Ø",
    "f.lastRunMax": "посл. макс",
]

// Indonesisch-Overlay (71 Keys). Fallback: Englisch.
let wIdOverlay: [String: String] = [
    "rec.paused": "Dijeda",
    "rec.keepOpen": "biarkan aplikasi terbuka!",
    "rec.locPerm": "Lokasi tidak diizinkan – tidak bisa merekam",
    "rec.locCoarse": "Hanya lokasi perkiraan – izinkan “Tepat”",
    "pair.title": "Hubungkan jam",
    "pair.howto": "Buat kode pairing dan masukkan di pumpfoil.org (Akun).",
    "pair.gen": "Buat kode pairing",
    "pair.enterOn": "Masukkan di pumpfoil.org:",
    "pair.waiting": "menunggu konfirmasi…",
    "pair.later": "Hubungkan nanti",
    "rec.start": "Mulai",
    "rec.stop": "Stop",
    "rec.stopHold": "Stop · tahan 2 s",
    "rec.starting": "memulai…",
    "rec.autoStart": "Mulai otomatis aktif",
    "rec.autoStartToggle": "Mulai otomatis",
    "rec.autoStartHelp": "Mulai otomatis di 10 km/h – kalau Anda lupa.",
    "rec.recording": "Merekam",
    "rec.saving": "menyimpan…",
    "rec.saved": "tersimpan",
    "rec.workoutFail": "Mulai workout gagal: ",
    "rec.sync": "Sinkron…",
    "rec.notNow": "Nanti saja",
    "rec.toData": "Bidang data →",
    "rec.toSummary": "← Ringkasan",
    "rec.notLinked": "Tak tertaut – sesi lokal",
    "rec.connect": "Hubungkan",
    "rec.pendingUpload": "menunggu unggah",
    "rec.uploadNow": "Unggah sekarang",
    "rec.waitConn": "menunggu koneksi",
    "rec.willResume": "akan lanjut",
    "rec.uploading": "mengunggah",
    "rec.serverErr": "Kesalahan server – coba lagi nanti",
    "rec.authErr": "Tautan tidak valid – hubungkan ulang",
    "rec.repair": "Hubungkan ulang",
    "rec.switch": "Ganti akun",
    "rec.alarm": "Alarm",
    "rec.change": "ubah",
    "rec.holdProgress": "tahan…",
    "foil.choose": "Pilih foil",
    "foil.chooseHelp": "Menyimpan foil Anda ke sesi ini dan menyetel ambang alarm bila sumber disetel ke Foil.",
    "foil.prefix": "Foil: ",
    "foil.alarm": "Alarm",
    "foil.alarmOn": "Alarm getar",
    "foil.alarmHelp": "Bergetar bila Anda di atas atau di bawah rentang kecepatan optimal foil Anda.",
    "foil.thresholds": "Ambang",
    "foil.source": "Sumber",
    "foil.auto": "Auto (foil)",
    "foil.manual": "Manual",
    "foil.min": "Min",
    "foil.max": "Maks",
    "foil.noFoil": "Tanpa foil",
    "foil.fixed": "Nilai tetap",
    "foil.none": "Tanpa foil",
    "foil.noneSub": "tanpa alarm",
    "foil.trigger": "Pemicu",
    "foil.continuous": "Terus-menerus",
    "common.cancel": "Batal",
    "f.kmh3s": "km/h (3s)",
    "f.kmh": "km/h",
    "f.kmhAvg": "Ø km/h",
    "f.kmhMax": "maks km/h",
    "f.bpm": "bpm",
    "f.bpmAvg": "Ø bpm",
    "f.bpmMax": "maks bpm",
    "f.time": "Waktu",
    "f.clock": "Jam",
    "f.alt": "Ketinggian",
    "f.temp": "Suhu",
    "f.ascent": "Pendakian",
    "f.runTime": "Waktu lintasan",
    "f.runDist": "Jarak lintasan",
    "f.runs": "Lintasan",
    "f.lastRunTime": "waktu terakhir",
    "f.lastRunDist": "jarak terakhir",
    "f.lastRunAvg": "Ø terakhir",
    "f.lastRunMax": "maks terakhir",
]

// Norwegisch (Bokmål) — Overlay wie die anderen Zusatzsprachen: Overlay → Englisch → Deutsch.
// Kam mit dem ersten norwegischen Nutzer (Sogndal, 05.08.2026) dazu; Bokmål deckt auch
// nn-/no-Geräte ab (siehe web/src/i18n/index.tsx).
let wNbOverlay: [String: String] = [
    "menu.layouts": "Egne oppsett",
    "common.auto": "Automatisk",
    "common.on": "På",
    "common.off": "Av",
    "lay.none": "ingen sider",
    "rec.paused": "Pauset",
    "pair.title": "Koble til klokke",
    "pair.howto": "Lag en koblingskode og skriv den inn på pumpfoil.org (Konto).",
    "pair.gen": "Lag koblingskode",
    "pair.enterOn": "Skriv på pumpfoil.org:",
    "pair.waiting": "venter på bekreftelse…",
    "pair.later": "Koble senere",
    "rec.start": "Start",
    "rec.stop": "Stopp",
    "rec.stopHold": "Stopp · hold 2 s",
    "rec.discardHold": "Forkast · hold 2 s",
    "rec.starting": "starter…",
    "rec.autoStart": "Auto-start på",
    "rec.autoStartToggle": "Auto-start",
    "rec.autoStartHelp": "Starter selv ved 10 km/h – hvis du glemmer det.",
    "rec.recording": "Opptak",
    "rec.saving": "lagrer…",
    "rec.saved": "lagret",
    "rec.workoutFail": "Start av økt feilet: ",
    "rec.sync": "Synk…",
    "rec.notNow": "Ikke nå",
    "rec.toData": "Datafelt →",
    "rec.toSummary": "← Oversikt",
    "rec.notLinked": "Ikke koblet – økter lokalt",
    "rec.connect": "Koble til",
    "rec.pendingUpload": "skal lastes opp",
    "rec.uploadNow": "Last opp nå",
    "rec.waitConn": "venter på tilkobling",
    "rec.willResume": "fortsetter",
    "rec.uploading": "laster opp",
    "rec.locPerm": "Posisjon ikke tillatt – opptak ikke mulig",
    "rec.locCoarse": "Bare omtrentlig posisjon – tillat “Presis”",
    "rec.keepOpen": "hold appen åpen!",
    "rec.serverErr": "Serverfeil – prøv senere",
    "rec.authErr": "Ugyldig kobling – koble igjen",
    "rec.repair": "Koble igjen",
    "rec.switch": "Bytt konto",
    "rec.alarm": "Alarm",
    "rec.change": "endre",
    "rec.holdProgress": "hold…",
    "foil.choose": "Velg foil",
    "foil.chooseHelp": "Lagrer foilen din i denne økta og setter alarmgrensene når kilden er satt til Foil.",
    "foil.prefix": "Foil: ",
    "foil.alarm": "Alarm",
    "foil.alarmOn": "Vibrasjonsalarm",
    "foil.alarmHelp": "Vibrerer når du går over eller under foilens optimale fartsområde.",
    "foil.thresholds": "Grenser",
    "foil.source": "Kilde",
    "foil.auto": "Auto (foil)",
    "foil.manual": "Manuell",
    "foil.min": "Min",
    "foil.max": "Maks",
    "foil.noFoil": "Ingen foil",
    "foil.fixed": "Faste verdier",
    "foil.none": "Ingen foil",
    "foil.noneSub": "ingen alarm",
    "foil.trigger": "Utløser",
    "foil.continuous": "Gjentatt",
    "common.cancel": "Avbryt",
    "f.kmh3s": "km/h (3s)",
    "f.kmh": "km/h",
    "f.kmhAvg": "snitt km/h",
    "f.kmhMax": "maks km/h",
    "f.bpm": "bpm",
    "f.bpmAvg": "snitt bpm",
    "f.bpmMax": "maks bpm",
    "f.time": "Tid",
    "f.clock": "Klokke",
    "f.alt": "Høyde",
    "f.temp": "Temp",
    "f.ascent": "Stigning",
    "f.runTime": "Run-tid",
    "f.runDist": "Run dist",
    "f.runs": "Runs",
    "f.lastRunTime": "siste tid",
    "f.lastRunDist": "siste dist",
    "f.lastRunAvg": "siste snitt",
    "f.lastRunMax": "siste maks",
]

// nl-Overlay der Uhr (76 Schluessel), 31.08. Quellen in dieser
// Reihenfolge: watch/source/Strings.mc (Garmin, laengst im Store), dann die
// Web-Locales ueber den deutschen Text, dann eigene Uebersetzung der Kurztexte.
let wNlOverlay: [String: String] = [
    "foil.alarmHelp": "Trilt wanneer je boven of onder het optimale snelheidsbereik van je foil komt.",
    "foil.choose": "Foil & alarm",
    "foil.chooseHelp": "Slaat je foil bij deze sessie op en bepaalt de alarmdrempels als de bron op Foil staat.",
    "pair.later": "Annuleren",
    "rec.autoStartHelp": "Start vanaf 10 km/h vanzelf – voor als je het vergeet.",
    "rec.discardHold": "Verwerpen",
    "rec.locCoarse": "Alleen globale locatie – sta „Precies\" toe",
    "rec.locPerm": "Locatie ontbreekt – zonder locatie geen opname. Tik",
    "menu.layouts": "Eigen layouts",
    "common.auto": "Automatisch",
    "common.on": "Aan",
    "common.off": "Uit",
    "lay.none": "geen pagina's",
    "rec.paused": "Gepauzeerd",
    "pair.title": "Horloge koppelen",
    "pair.howto": "Maak een koppelcode en voer die in op pumpfoil.org (Account).",
    "pair.gen": "Koppelcode genereren",
    "pair.enterOn": "Invoeren op pumpfoil.org:",
    "pair.waiting": "wacht op bevestiging…",
    "rec.start": "Start",
    "rec.stop": "Stop",
    "rec.stopHold": "Vasthouden",
    "rec.starting": "starten…",
    "rec.autoStart": "Autostart aan",
    "rec.autoStartToggle": "auto-start",
    "rec.recording": "Opname loopt",
    "rec.saving": "opslaan…",
    "rec.saved": "opgeslagen",
    "rec.workoutFail": "Workout starten mislukt: ",
    "rec.sync": "Sync…",
    "rec.notNow": "Nu niet",
    "rec.toData": "Datavelden →",
    "rec.toSummary": "← Overzicht",
    "rec.notLinked": "Niet gekoppeld – sessies lokaal",
    "rec.connect": "Verbinden",
    "rec.pendingUpload": "wachten op upload",
    "rec.uploadNow": "Nu uploaden",
    "rec.waitConn": "wacht op verbinding",
    "rec.willResume": "wordt hervat",
    "rec.uploading": "uploaden",
    "rec.keepOpen": "houd de app open!",
    "rec.serverErr": "Serverfout – later opnieuw",
    "rec.authErr": "Koppeling ongeldig – opnieuw koppelen",
    "rec.repair": "Opnieuw koppelen",
    "rec.switch": "Account wisselen",
    "rec.alarm": "Alarm",
    "rec.change": "wijzigen",
    "rec.holdProgress": "vasthouden…",
    "foil.prefix": "Foil: ",
    "foil.alarm": "Alarm",
    "foil.alarmOn": "Trilalarm",
    "foil.thresholds": "Drempels",
    "foil.source": "Bron",
    "foil.auto": "Auto (foil)",
    "foil.manual": "Handmatig",
    "foil.min": "Min",
    "foil.max": "Max",
    "foil.noFoil": "Geen foil",
    "foil.fixed": "Vaste waarden",
    "foil.none": "Zonder alarm",
    "foil.noneSub": "geen alarm",
    "foil.trigger": "Activeren",
    "foil.continuous": "doorlopend",
    "common.cancel": "Annuleren",
    "f.kmh3s": "km/h (3s)",
    "f.kmh": "km/h",
    "f.kmhAvg": "Ø km/h",
    "f.kmhMax": "max km/h",
    "f.bpm": "bpm",
    "f.bpmAvg": "Ø bpm",
    "f.bpmMax": "max bpm",
    "f.time": "Tijd",
    "f.clock": "Klok",
    "f.alt": "Hoogte",
    "f.temp": "Temp",
    "f.ascent": "Stijging",
    "f.runTime": "Rit-tijd",
    "f.runDist": "Rit-afst",
    "f.runs": "Runs",
    "f.lastRunTime": "laatste tijd",
    "f.lastRunDist": "laatste afst",
    "f.lastRunAvg": "laatste Ø",
    "f.lastRunMax": "laatste max",
    "f.lastRunMaxHr": "laatste max bpm",
]

// fi-Overlay der Uhr (76 Schluessel), 31.08. Quellen in dieser
// Reihenfolge: watch/source/Strings.mc (Garmin, laengst im Store), dann die
// Web-Locales ueber den deutschen Text, dann eigene Uebersetzung der Kurztexte.
let wFiOverlay: [String: String] = [
    "foil.alarmHelp": "Värisee, kun ylität tai alitat foilisi optimaalisen nopeusalueen.",
    "foil.choose": "Foili & hälytys",
    "foil.chooseHelp": "Tallentaa foilisi tähän sessioon ja asettaa hälytysrajat, kun lähteeksi on valittu foili.",
    "pair.later": "Peruuta",
    "rec.autoStartHelp": "Käynnistyy itsestään 10 km/h:sta – siltä varalta että unohdat.",
    "rec.discardHold": "Hylkää",
    "rec.locCoarse": "Vain likimääräinen sijainti – salli „Tarkka\"",
    "rec.locPerm": "Sijaintilupa puuttuu – ilman sitä ei tallenneta. Napauta",
    "menu.layouts": "Omat asettelut",
    "common.auto": "Automaattinen",
    "common.on": "Päällä",
    "common.off": "Pois",
    "lay.none": "ei sivuja",
    "rec.paused": "Tauolla",
    "pair.title": "Yhdistä kello",
    "pair.howto": "Luo pariliitoskoodi ja syötä se osoitteessa pumpfoil.org (Tili).",
    "pair.gen": "Luo pariliitoskoodi",
    "pair.enterOn": "Syötä osoitteessa pumpfoil.org:",
    "pair.waiting": "odotetaan vahvistusta…",
    "rec.start": "Aloitus",
    "rec.stop": "Pysäytys",
    "rec.stopHold": "Pidä",
    "rec.starting": "käynnistetään…",
    "rec.autoStart": "Autom. käynnistys",
    "rec.autoStartToggle": "autom. start",
    "rec.recording": "Tallennus käynnissä",
    "rec.saving": "tallennetaan…",
    "rec.saved": "tallennettu",
    "rec.workoutFail": "Harjoituksen aloitus epäonnistui: ",
    "rec.sync": "Synk…",
    "rec.notNow": "Ei nyt",
    "rec.toData": "Tietokentät →",
    "rec.toSummary": "← Yhteenveto",
    "rec.notLinked": "Ei yhdistetty – sessiot laitteella",
    "rec.connect": "Yhdistä",
    "rec.pendingUpload": "odottaa lähetystä",
    "rec.uploadNow": "Lähetä nyt",
    "rec.waitConn": "odottaa yhteyttä",
    "rec.willResume": "jatkuu",
    "rec.uploading": "lähetetään",
    "rec.keepOpen": "pidä sovellus auki!",
    "rec.serverErr": "Palvelinvirhe – yritä myöhemmin",
    "rec.authErr": "Yhteys virheellinen – yhdistä uudelleen",
    "rec.repair": "Yhdistä uudelleen",
    "rec.switch": "Vaihda tiliä",
    "rec.alarm": "Hälytys",
    "rec.change": "muuta",
    "rec.holdProgress": "pidä…",
    "foil.prefix": "Foil: ",
    "foil.alarm": "Hälytys",
    "foil.alarmOn": "Värinähälytys",
    "foil.thresholds": "Kynnykset",
    "foil.source": "Lähde",
    "foil.auto": "Auto (foil)",
    "foil.manual": "Manuaalinen",
    "foil.min": "Min",
    "foil.max": "Maks",
    "foil.noFoil": "Ei foilia",
    "foil.fixed": "Kiinteät arvot",
    "foil.none": "Ei hälytystä",
    "foil.noneSub": "ei hälytystä",
    "foil.trigger": "Laukaisu",
    "foil.continuous": "jatkuva",
    "common.cancel": "Peruuta",
    "f.kmh3s": "km/h (3s)",
    "f.kmh": "km/h",
    "f.kmhAvg": "Ø km/h",
    "f.kmhMax": "maks km/h",
    "f.bpm": "bpm",
    "f.bpmAvg": "Ø bpm",
    "f.bpmMax": "maks bpm",
    "f.time": "Aika",
    "f.clock": "Kello",
    "f.alt": "Korkeus",
    "f.temp": "Lämpö",
    "f.ascent": "Nousu",
    "f.runTime": "Vedon aika",
    "f.runDist": "Vedon matka",
    "f.runs": "Vedot",
    "f.lastRunTime": "ed. aika",
    "f.lastRunDist": "ed. matka",
    "f.lastRunAvg": "ed. Ø",
    "f.lastRunMax": "ed. maks",
    "f.lastRunMaxHr": "ed. maks bpm",
]

// cs-Overlay der Uhr (76 Schluessel), 31.08. Quellen in dieser
// Reihenfolge: watch/source/Strings.mc (Garmin, laengst im Store), dann die
// Web-Locales ueber den deutschen Text, dann eigene Uebersetzung der Kurztexte.
let wCsOverlay: [String: String] = [
    "foil.alarmHelp": "Zavibruje, když překročíš nebo klesneš pod optimální rychlostní rozsah svého foilu.",
    "foil.choose": "Foil a alarm",
    "foil.chooseHelp": "Uloží tvůj foil k této relaci a nastaví prahy alarmu, když je jako zdroj zvolen foil.",
    "pair.later": "Zrušit",
    "rec.autoStartHelp": "Spustí se sám od 10 km/h – kdyby ses zapomněl.",
    "rec.discardHold": "Zahodit",
    "rec.locCoarse": "Jen přibližná poloha – povol „Přesnou\"",
    "rec.locPerm": "Chybí poloha – bez ní se nenahrává. Klepni",
    "menu.layouts": "Vlastní rozvržení",
    "common.auto": "Automaticky",
    "common.on": "Zap",
    "common.off": "Vyp",
    "lay.none": "žádné strany",
    "rec.paused": "Pozastaveno",
    "pair.title": "Připojit hodinky",
    "pair.howto": "Vytvoř párovací kód a zadej ho na pumpfoil.org (Účet).",
    "pair.gen": "Vytvořit párovací kód",
    "pair.enterOn": "Zadej na pumpfoil.org:",
    "pair.waiting": "čeká se na potvrzení…",
    "rec.start": "Start",
    "rec.stop": "Stop",
    "rec.stopHold": "Držet",
    "rec.starting": "spouštím…",
    "rec.autoStart": "Autostart zapnut",
    "rec.autoStartToggle": "autostart",
    "rec.recording": "Nahrávání běží",
    "rec.saving": "ukládám…",
    "rec.saved": "uloženo",
    "rec.workoutFail": "Spuštění tréninku selhalo: ",
    "rec.sync": "Synch…",
    "rec.notNow": "Teď ne",
    "rec.toData": "Datová pole →",
    "rec.toSummary": "← Přehled",
    "rec.notLinked": "Nepřipojeno – relace lokálně",
    "rec.connect": "Připojit",
    "rec.pendingUpload": "čekají na nahrání",
    "rec.uploadNow": "Nahrát teď",
    "rec.waitConn": "čeká na spojení",
    "rec.willResume": "bude pokračovat",
    "rec.uploading": "nahrává se",
    "rec.keepOpen": "nech aplikaci otevřenou!",
    "rec.serverErr": "Chyba serveru – zkus později",
    "rec.authErr": "Spojení neplatné – připoj znovu",
    "rec.repair": "Připojit znovu",
    "rec.switch": "Změnit účet",
    "rec.alarm": "Alarm",
    "rec.change": "změnit",
    "rec.holdProgress": "drž…",
    "foil.prefix": "Foil: ",
    "foil.alarm": "Alarm",
    "foil.alarmOn": "Vibrační alarm",
    "foil.thresholds": "Prahy",
    "foil.source": "Zdroj",
    "foil.auto": "Auto (foil)",
    "foil.manual": "Ručně",
    "foil.min": "Min",
    "foil.max": "Max",
    "foil.noFoil": "Bez foilu",
    "foil.fixed": "Pevné hodnoty",
    "foil.none": "Bez alarmu",
    "foil.noneSub": "bez alarmu",
    "foil.trigger": "Spouštění",
    "foil.continuous": "trvale",
    "common.cancel": "Zrušit",
    "f.kmh3s": "km/h (3s)",
    "f.kmh": "km/h",
    "f.kmhAvg": "Ø km/h",
    "f.kmhMax": "max km/h",
    "f.bpm": "bpm",
    "f.bpmAvg": "Ø bpm",
    "f.bpmMax": "max bpm",
    "f.time": "Čas",
    "f.clock": "Hodiny",
    "f.alt": "Nadmořská výška",
    "f.temp": "Tepl",
    "f.ascent": "Stoupání",
    "f.runTime": "Čas jízdy",
    "f.runDist": "Vzdál. jízdy",
    "f.runs": "Jízdy",
    "f.lastRunTime": "posl. čas",
    "f.lastRunDist": "posl. vzdál",
    "f.lastRunAvg": "posl. Ø",
    "f.lastRunMax": "posl. max",
    "f.lastRunMaxHr": "posl. max bpm",
]
