import Foundation

// Zusätzliche Overlays für den watchOS-Recorder (WLoc) — pt/ja/zh/ru/id.
// Eigene Datei (wie LocExtra.swift auf iOS). Fallback je Key: Englisch (siehe WLoc.t).

// Portugiesisch-Overlay (71 Keys). Fallback: Englisch.
let wPtOverlay: [String: String] = [
    "pair.title": "Conectar relógio",
    "pair.howto": "Gere um código de pareamento e digite-o no pumpfoil.org (Conta).",
    "pair.gen": "Gerar código de pareamento",
    "pair.enterOn": "Digite no pumpfoil.org:",
    "pair.waiting": "aguardando confirmação…",
    "pair.later": "Conectar depois",
    "rec.start": "Iniciar",
    "rec.stop": "Parar",
    "rec.stopHold": "Parar · segure 3 s",
    "rec.starting": "iniciando…",
    "rec.autoStart": "Auto-início ligado",
    "rec.autoStartToggle": "Auto-início",
    "rec.autoStartHelp": "Inicia sozinho a 10 km/h – caso você esqueça.",
    "rec.recording": "Gravando",
    "rec.saving": "salvando…",
    "rec.saved": "salvo",
    "rec.workoutFail": "Falha ao iniciar o treino: ",
    "rec.sync": "Sincr.…",
    "rec.notNow": "Agora não",
    "rec.toData": "Campos de dados →",
    "rec.toSummary": "← Resumo",
    "rec.notLinked": "Não vinculado – sessões locais",
    "rec.connect": "Conectar",
    "rec.pendingUpload": "aguardando envio",
    "rec.uploadNow": "Enviar agora",
    "rec.waitConn": "aguardando conexão",
    "rec.willResume": "vai retomar",
    "rec.uploading": "enviando",
    "rec.serverErr": "Erro no servidor – tente depois",
    "rec.authErr": "Vínculo inválido – reconecte",
    "rec.repair": "Reconectar",
    "rec.switch": "Trocar de conta",
    "rec.alarm": "Alarme",
    "rec.change": "alterar",
    "rec.holdProgress": "segure…",
    "foil.choose": "Escolher foil",
    "foil.chooseHelp": "Salva seu foil nesta sessão e define os limites do alarme quando a fonte está em Foil.",
    "foil.prefix": "Foil: ",
    "foil.alarm": "Alarme",
    "foil.alarmOn": "Alarme por vibração",
    "foil.alarmHelp": "Vibra quando você passa acima ou abaixo da faixa de velocidade ideal do seu foil.",
    "foil.thresholds": "Limites",
    "foil.source": "Fonte",
    "foil.auto": "Auto (foil)",
    "foil.manual": "Manual",
    "foil.min": "Mín.",
    "foil.max": "Máx.",
    "foil.noFoil": "Sem foil",
    "foil.fixed": "Valores fixos",
    "foil.none": "Sem foil",
    "foil.noneSub": "sem alarme",
    "foil.trigger": "Disparo",
    "foil.continuous": "Contínuo",
    "common.cancel": "Cancelar",
    "f.kmh3s": "km/h (3s)",
    "f.kmh": "km/h",
    "f.kmhAvg": "km/h méd.",
    "f.kmhMax": "km/h máx.",
    "f.bpm": "bpm",
    "f.bpmAvg": "bpm méd.",
    "f.bpmMax": "bpm máx.",
    "f.time": "Tempo",
    "f.clock": "Relógio",
    "f.alt": "Altitude",
    "f.temp": "Temp.",
    "f.ascent": "Subida",
    "f.runTime": "Tempo run",
    "f.runDist": "Dist. run",
    "f.runs": "Runs",
    "f.lastRunTime": "últ. tempo",
    "f.lastRunDist": "últ. dist.",
    "f.lastRunAvg": "últ. méd.",
    "f.lastRunMax": "últ. máx.",
]

// Japanisch-Overlay (71 Keys). Fallback: Englisch.
let wJaOverlay: [String: String] = [
    "pair.title": "ウォッチを接続",
    "pair.howto": "ペアリングコードを生成し、pumpfoil.org(アカウント)で入力します。",
    "pair.gen": "ペアリングコードを生成",
    "pair.enterOn": "pumpfoil.orgで入力:",
    "pair.waiting": "確認待ち…",
    "pair.later": "後で接続",
    "rec.start": "スタート",
    "rec.stop": "ストップ",
    "rec.stopHold": "停止 · 3秒長押し",
    "rec.starting": "開始中…",
    "rec.autoStart": "自動スタート オン",
    "rec.autoStartToggle": "自動スタート",
    "rec.autoStartHelp": "10 km/hで自動スタート—忘れても安心。",
    "rec.recording": "記録中",
    "rec.saving": "保存中…",
    "rec.saved": "保存しました",
    "rec.workoutFail": "ワークアウト開始失敗: ",
    "rec.sync": "同期…",
    "rec.notNow": "後で",
    "rec.toData": "データ画面 →",
    "rec.toSummary": "← サマリー",
    "rec.notLinked": "未連携 – セッションはローカル",
    "rec.connect": "接続",
    "rec.pendingUpload": "アップロード待ち",
    "rec.uploadNow": "今すぐアップロード",
    "rec.waitConn": "接続待ち",
    "rec.willResume": "再開します",
    "rec.uploading": "アップロード中",
    "rec.serverErr": "サーバーエラー – 後で再試行",
    "rec.authErr": "連携が無効 – 再接続",
    "rec.repair": "再接続",
    "rec.switch": "アカウント切替",
    "rec.alarm": "アラーム",
    "rec.change": "変更",
    "rec.holdProgress": "長押し…",
    "foil.choose": "フォイルを選択",
    "foil.chooseHelp": "フォイルをこのセッションに保存し、ソースがフォイルの場合はアラームのしきい値を設定します。",
    "foil.prefix": "フォイル: ",
    "foil.alarm": "アラーム",
    "foil.alarmOn": "バイブアラーム",
    "foil.alarmHelp": "フォイルの最適速度域を上回る・下回ると振動します。",
    "foil.thresholds": "しきい値",
    "foil.source": "ソース",
    "foil.auto": "自動(フォイル)",
    "foil.manual": "手動",
    "foil.min": "最小",
    "foil.max": "最大",
    "foil.noFoil": "フォイルなし",
    "foil.fixed": "固定値",
    "foil.none": "フォイルなし",
    "foil.noneSub": "アラームなし",
    "foil.trigger": "トリガー",
    "foil.continuous": "連続",
    "common.cancel": "キャンセル",
    "f.kmh3s": "km/h(3秒)",
    "f.kmh": "km/h",
    "f.kmhAvg": "平均 km/h",
    "f.kmhMax": "最高 km/h",
    "f.bpm": "bpm",
    "f.bpmAvg": "平均 bpm",
    "f.bpmMax": "最高 bpm",
    "f.time": "時間",
    "f.clock": "時計",
    "f.alt": "高度",
    "f.temp": "気温",
    "f.ascent": "上昇",
    "f.runTime": "ラン時間",
    "f.runDist": "ラン距離",
    "f.runs": "ラン",
    "f.lastRunTime": "前回時間",
    "f.lastRunDist": "前回距離",
    "f.lastRunAvg": "前回平均",
    "f.lastRunMax": "前回最高",
]

// Chinesisch (vereinfacht)-Overlay (71 Keys). Fallback: Englisch.
let wZhOverlay: [String: String] = [
    "pair.title": "连接手表",
    "pair.howto": "生成配对码，在 pumpfoil.org（账户）中输入。",
    "pair.gen": "生成配对码",
    "pair.enterOn": "在 pumpfoil.org 输入：",
    "pair.waiting": "等待确认…",
    "pair.later": "稍后连接",
    "rec.start": "开始",
    "rec.stop": "停止",
    "rec.stopHold": "停止 · 长按 3 s",
    "rec.starting": "启动中…",
    "rec.autoStart": "自动开始：开",
    "rec.autoStartToggle": "自动开始",
    "rec.autoStartHelp": "10 km/h 时自动开始 — 以防你忘记。",
    "rec.recording": "记录中",
    "rec.saving": "保存中…",
    "rec.saved": "已保存",
    "rec.workoutFail": "训练启动失败： ",
    "rec.sync": "同步…",
    "rec.notNow": "暂不",
    "rec.toData": "数据字段 →",
    "rec.toSummary": "← 摘要",
    "rec.notLinked": "未连接 — 记录仅在本地",
    "rec.connect": "连接",
    "rec.pendingUpload": "待上传",
    "rec.uploadNow": "立即上传",
    "rec.waitConn": "等待连接",
    "rec.willResume": "将恢复",
    "rec.uploading": "上传中",
    "rec.serverErr": "服务器错误 — 稍后重试",
    "rec.authErr": "连接失效 — 请重连",
    "rec.repair": "重新连接",
    "rec.switch": "切换账户",
    "rec.alarm": "提醒",
    "rec.change": "更改",
    "rec.holdProgress": "长按…",
    "foil.choose": "选择 foil",
    "foil.chooseHelp": "将 foil 保存到本次记录，并在来源设为 Foil 时设定提醒阈值。",
    "foil.prefix": "Foil： ",
    "foil.alarm": "提醒",
    "foil.alarmOn": "震动提醒",
    "foil.alarmHelp": "当你高于或低于 foil 最佳速度区间时震动。",
    "foil.thresholds": "阈值",
    "foil.source": "来源",
    "foil.auto": "自动（foil）",
    "foil.manual": "手动",
    "foil.min": "最低",
    "foil.max": "最高",
    "foil.noFoil": "无 foil",
    "foil.fixed": "固定值",
    "foil.none": "无 foil",
    "foil.noneSub": "无提醒",
    "foil.trigger": "触发",
    "foil.continuous": "持续",
    "common.cancel": "取消",
    "f.kmh3s": "km/h（3秒）",
    "f.kmh": "km/h",
    "f.kmhAvg": "平均 km/h",
    "f.kmhMax": "最高 km/h",
    "f.bpm": "bpm",
    "f.bpmAvg": "平均 bpm",
    "f.bpmMax": "最高 bpm",
    "f.time": "时间",
    "f.clock": "时钟",
    "f.alt": "海拔",
    "f.temp": "温度",
    "f.ascent": "爬升",
    "f.runTime": "航次时长",
    "f.runDist": "航次距离",
    "f.runs": "航次",
    "f.lastRunTime": "上次时长",
    "f.lastRunDist": "上次距离",
    "f.lastRunAvg": "上次平均",
    "f.lastRunMax": "上次最高",
]

// Russisch-Overlay (71 Keys). Fallback: Englisch.
let wRuOverlay: [String: String] = [
    "pair.title": "Подключить часы",
    "pair.howto": "Сгенерируйте код сопряжения и введите его на pumpfoil.org (Аккаунт).",
    "pair.gen": "Сгенерировать код",
    "pair.enterOn": "Введите на pumpfoil.org:",
    "pair.waiting": "ждём подтверждения…",
    "pair.later": "Позже",
    "rec.start": "Старт",
    "rec.stop": "Стоп",
    "rec.stopHold": "Стоп · держите 3 с",
    "rec.starting": "запуск…",
    "rec.autoStart": "Автостарт вкл",
    "rec.autoStartToggle": "Автостарт",
    "rec.autoStartHelp": "Автостарт при 10 км/ч — если забудете.",
    "rec.recording": "Запись",
    "rec.saving": "сохранение…",
    "rec.saved": "сохранено",
    "rec.workoutFail": "Ошибка запуска тренировки: ",
    "rec.sync": "Синхр…",
    "rec.notNow": "Не сейчас",
    "rec.toData": "Поля данных →",
    "rec.toSummary": "← Итоги",
    "rec.notLinked": "Не привязано — локально",
    "rec.connect": "Подключить",
    "rec.pendingUpload": "ждёт загрузки",
    "rec.uploadNow": "Загрузить",
    "rec.waitConn": "ждём связь",
    "rec.willResume": "продолжится",
    "rec.uploading": "загрузка",
    "rec.serverErr": "Ошибка сервера — позже",
    "rec.authErr": "Привязка недействительна — заново",
    "rec.repair": "Переподключить",
    "rec.switch": "Сменить аккаунт",
    "rec.alarm": "Сигнал",
    "rec.change": "изменить",
    "rec.holdProgress": "держите…",
    "foil.choose": "Выбрать foil",
    "foil.chooseHelp": "Сохраняет foil для этой сессии и задаёт пороги сигнала, когда источник — Foil.",
    "foil.prefix": "Foil: ",
    "foil.alarm": "Сигнал",
    "foil.alarmOn": "Виброзвонок",
    "foil.alarmHelp": "Вибрирует, когда вы выходите за оптимальный диапазон скорости foil.",
    "foil.thresholds": "Пороги",
    "foil.source": "Источник",
    "foil.auto": "Авто (foil)",
    "foil.manual": "Вручную",
    "foil.min": "Мин",
    "foil.max": "Макс",
    "foil.noFoil": "Без foil",
    "foil.fixed": "Фикс. значения",
    "foil.none": "Без foil",
    "foil.noneSub": "без сигнала",
    "foil.trigger": "Триггер",
    "foil.continuous": "Постоянно",
    "common.cancel": "Отмена",
    "f.kmh3s": "км/ч (3с)",
    "f.kmh": "км/ч",
    "f.kmhAvg": "Ø км/ч",
    "f.kmhMax": "макс км/ч",
    "f.bpm": "уд/мин",
    "f.bpmAvg": "Ø уд/мин",
    "f.bpmMax": "макс уд/мин",
    "f.time": "Время",
    "f.clock": "Часы",
    "f.alt": "Высота",
    "f.temp": "Темп",
    "f.ascent": "Набор",
    "f.runTime": "Время заезда",
    "f.runDist": "Дист. заезда",
    "f.runs": "Заезды",
    "f.lastRunTime": "посл. время",
    "f.lastRunDist": "посл. дист.",
    "f.lastRunAvg": "посл. Ø",
    "f.lastRunMax": "посл. макс",
]

// Indonesisch-Overlay (71 Keys). Fallback: Englisch.
let wIdOverlay: [String: String] = [
    "pair.title": "Hubungkan jam",
    "pair.howto": "Buat kode pairing dan masukkan di pumpfoil.org (Akun).",
    "pair.gen": "Buat kode pairing",
    "pair.enterOn": "Masukkan di pumpfoil.org:",
    "pair.waiting": "menunggu konfirmasi…",
    "pair.later": "Hubungkan nanti",
    "rec.start": "Mulai",
    "rec.stop": "Stop",
    "rec.stopHold": "Stop · tahan 3 s",
    "rec.starting": "memulai…",
    "rec.autoStart": "Mulai otomatis aktif",
    "rec.autoStartToggle": "Mulai otomatis",
    "rec.autoStartHelp": "Mulai otomatis di 10 km/h – kalau Anda lupa.",
    "rec.recording": "Merekam",
    "rec.saving": "menyimpan…",
    "rec.saved": "tersimpan",
    "rec.workoutFail": "Mulai workout gagal: ",
    "rec.sync": "Sinkron…",
    "rec.notNow": "Nanti saja",
    "rec.toData": "Bidang data →",
    "rec.toSummary": "← Ringkasan",
    "rec.notLinked": "Tak tertaut – sesi lokal",
    "rec.connect": "Hubungkan",
    "rec.pendingUpload": "menunggu unggah",
    "rec.uploadNow": "Unggah sekarang",
    "rec.waitConn": "menunggu koneksi",
    "rec.willResume": "akan lanjut",
    "rec.uploading": "mengunggah",
    "rec.serverErr": "Kesalahan server – coba lagi nanti",
    "rec.authErr": "Tautan tidak valid – hubungkan ulang",
    "rec.repair": "Hubungkan ulang",
    "rec.switch": "Ganti akun",
    "rec.alarm": "Alarm",
    "rec.change": "ubah",
    "rec.holdProgress": "tahan…",
    "foil.choose": "Pilih foil",
    "foil.chooseHelp": "Menyimpan foil Anda ke sesi ini dan menyetel ambang alarm bila sumber disetel ke Foil.",
    "foil.prefix": "Foil: ",
    "foil.alarm": "Alarm",
    "foil.alarmOn": "Alarm getar",
    "foil.alarmHelp": "Bergetar bila Anda di atas atau di bawah rentang kecepatan optimal foil Anda.",
    "foil.thresholds": "Ambang",
    "foil.source": "Sumber",
    "foil.auto": "Auto (foil)",
    "foil.manual": "Manual",
    "foil.min": "Min",
    "foil.max": "Maks",
    "foil.noFoil": "Tanpa foil",
    "foil.fixed": "Nilai tetap",
    "foil.none": "Tanpa foil",
    "foil.noneSub": "tanpa alarm",
    "foil.trigger": "Pemicu",
    "foil.continuous": "Terus-menerus",
    "common.cancel": "Batal",
    "f.kmh3s": "km/h (3s)",
    "f.kmh": "km/h",
    "f.kmhAvg": "Ø km/h",
    "f.kmhMax": "maks km/h",
    "f.bpm": "bpm",
    "f.bpmAvg": "Ø bpm",
    "f.bpmMax": "maks bpm",
    "f.time": "Waktu",
    "f.clock": "Jam",
    "f.alt": "Ketinggian",
    "f.temp": "Suhu",
    "f.ascent": "Pendakian",
    "f.runTime": "Waktu lintasan",
    "f.runDist": "Jarak lintasan",
    "f.runs": "Lintasan",
    "f.lastRunTime": "waktu terakhir",
    "f.lastRunDist": "jarak terakhir",
    "f.lastRunAvg": "Ø terakhir",
    "f.lastRunMax": "maks terakhir",
]
