"""Beschriftung der Teilen-Karte je Sprache — ERZEUGT von scripts/i18n-sharecard.py.

NICHT von Hand aendern: Quelle sind die Web-Sprachdateien (`share.*` in
web/src/i18n/locales/*.ts), damit der Teilen-Dialog und das gerenderte PNG nie
verschiedene Woerter zeigen. Nach einer Textaenderung dort das Skript neu laufen lassen.

Japanisch und Chinesisch tragen hier ENGLISCHE Texte, und das ist Absicht: die
Kartenschrift (DejaVuSans) hat keine CJK-Zeichen, und die einzige CJK-Schrift auf dem
Server (DroidSansFallbackFull) hat kein Latein, keine Ziffern und keinen Schraegstrich.
Ein gemischtes Label kaeme in jedem Fall teils als leere Kaestchen heraus.
"""
from __future__ import annotations

LABELS: dict[str, dict[str, str]] = {
    "cs": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Jízdy',
        "share.stat.pumps": 'Pumpy',
        "share.stat.avgspeed": 'Ø Rychlost',
        "share.stat.speed": 'Max. rychlost',
        "share.stat.time": 'Čas na foilu',
        "share.stat.longest": 'Nejdelší',
        "share.stat.distance": 'Vzdálenost/pump',
        "share.stat.pumprate": 'Ø Pumpy/min',
        "share.run": 'Jízda {n}',
    },
    "de": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Läufe',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Speed',
        "share.stat.speed": 'Top-Speed',
        "share.stat.time": 'Foil-Zeit',
        "share.stat.longest": 'Längster',
        "share.stat.distance": 'Strecke/Pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Lauf {n}',
    },
    "de-AT": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Läufe',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Speed',
        "share.stat.speed": 'Top-Speed',
        "share.stat.time": 'Foil-Zeit',
        "share.stat.longest": 'Längster',
        "share.stat.distance": 'Strecke/Pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Lauf {n}',
    },
    "en": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Runs',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Speed',
        "share.stat.speed": 'Top speed',
        "share.stat.time": 'Foil time',
        "share.stat.longest": 'Longest',
        "share.stat.distance": 'Distance/pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Run {n}',
    },
    "es": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Runs',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Velocidad',
        "share.stat.speed": 'Vel. máxima',
        "share.stat.time": 'Tiempo foil',
        "share.stat.longest": 'Más largo',
        "share.stat.distance": 'Distancia/pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Run {n}',
    },
    "fi": {
        "share.stat.foiling": 'Foilaus',
        "share.stat.runs": 'Vedot',
        "share.stat.pumps": 'Pumput',
        "share.stat.avgspeed": 'Ø Nopeus',
        "share.stat.speed": 'Huippunopeus',
        "share.stat.time": 'Foilaika',
        "share.stat.longest": 'Pisin',
        "share.stat.distance": 'Matka/pumppu',
        "share.stat.pumprate": 'Ø Pumput/min',
        "share.run": 'Veto {n}',
    },
    "fr": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Runs',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Vitesse',
        "share.stat.speed": 'Vitesse max',
        "share.stat.time": 'Temps foil',
        "share.stat.longest": 'Plus long',
        "share.stat.distance": 'Distance/pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Run {n}',
    },
    "gsw": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Läuf',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Speed',
        "share.stat.speed": 'Top-Speed',
        "share.stat.time": 'Foil-Ziit',
        "share.stat.longest": 'Längschte',
        "share.stat.distance": 'Strecki/Pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Lauf {n}',
    },
    "id": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Run',
        "share.stat.pumps": 'Pump',
        "share.stat.avgspeed": 'Ø Kecepatan',
        "share.stat.speed": 'Kecepatan maks',
        "share.stat.time": 'Waktu foil',
        "share.stat.longest": 'Terpanjang',
        "share.stat.distance": 'Jarak/pump',
        "share.stat.pumprate": 'Ø Pump/mnt',
        "share.run": 'Run {n}',
    },
    "it": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Run',
        "share.stat.pumps": 'Pump',
        "share.stat.avgspeed": 'Ø Velocità',
        "share.stat.speed": 'Velocità max',
        "share.stat.time": 'Tempo foil',
        "share.stat.longest": 'Più lungo',
        "share.stat.distance": 'Distanza/pump',
        "share.stat.pumprate": 'Ø Pump/min',
        "share.run": 'Run {n}',
    },
    "ja": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Runs',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Speed',
        "share.stat.speed": 'Top speed',
        "share.stat.time": 'Foil time',
        "share.stat.longest": 'Longest',
        "share.stat.distance": 'Distance/pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Run {n}',
    },
    "nb": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Runs',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Fart',
        "share.stat.speed": 'Toppfart',
        "share.stat.time": 'Foiltid',
        "share.stat.longest": 'Lengste',
        "share.stat.distance": 'Distanse/pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Run {n}',
    },
    "nl": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Runs',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Snelheid',
        "share.stat.speed": 'Topsnelheid',
        "share.stat.time": 'Foiltijd',
        "share.stat.longest": 'Langste',
        "share.stat.distance": 'Afstand/pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Run {n}',
    },
    "pl": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Przejazdy',
        "share.stat.pumps": 'Pompy',
        "share.stat.avgspeed": 'Ø Prędkość',
        "share.stat.speed": 'Maks. prędkość',
        "share.stat.time": 'Czas na foilu',
        "share.stat.longest": 'Najdłuższy',
        "share.stat.distance": 'Dystans/pompę',
        "share.stat.pumprate": 'Ø Pompy/min',
        "share.run": 'Przejazd {n}',
    },
    "pt": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Runs',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Velocidade',
        "share.stat.speed": 'Vel. máxima',
        "share.stat.time": 'Tempo de foil',
        "share.stat.longest": 'Mais longo',
        "share.stat.distance": 'Distância/pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Run {n}',
    },
    "pt-PT": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Runs',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Velocidade',
        "share.stat.speed": 'Vel. máxima',
        "share.stat.time": 'Tempo de foil',
        "share.stat.longest": 'Mais longo',
        "share.stat.distance": 'Distância/pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Run {n}',
    },
    "ru": {
        "share.stat.foiling": 'Фойлинг',
        "share.stat.runs": 'Заезды',
        "share.stat.pumps": 'Пампы',
        "share.stat.avgspeed": 'Ø Скорость',
        "share.stat.speed": 'Макс. скорость',
        "share.stat.time": 'Время фойла',
        "share.stat.longest": 'Длиннейший',
        "share.stat.distance": 'Дистанция/памп',
        "share.stat.pumprate": 'Ø Пампы/мин',
        "share.run": 'Заезд {n}',
    },
    "zh": {
        "share.stat.foiling": 'Foiling',
        "share.stat.runs": 'Runs',
        "share.stat.pumps": 'Pumps',
        "share.stat.avgspeed": 'Ø Speed',
        "share.stat.speed": 'Top speed',
        "share.stat.time": 'Foil time',
        "share.stat.longest": 'Longest',
        "share.stat.distance": 'Distance/pump',
        "share.stat.pumprate": 'Ø Pumps/min',
        "share.run": 'Run {n}',
    },
}


def t(key: str, lang: str | None) -> str:
    """Ein Kartentext. Unbekannte Sprache -> Englisch (nicht Deutsch), fehlender
    Schluessel -> Englisch, sonst der Schluessel selbst."""
    tab = LABELS.get(lang or "") or LABELS["en"]
    return tab.get(key) or LABELS["en"].get(key) or key
