import Foundation

// Lokalisierung nach Profil-Sprache (in UserDefaults "appLang", gesetzt nach Login).
// NICHT Geräte-Locale. Fallback de. Wording wie web/src/i18n/locales/*.
enum Loc {
    static let langs = ["de", "gsw", "de-AT", "en", "fr", "it", "es"]

    static func t(_ key: String, _ lang: String) -> String {
        guard let row = table[key] else { return key }
        return row[lang] ?? row["de"] ?? row["en"] ?? key
    }

    private static func r(_ de: String, _ gsw: String, _ deAT: String, _ en: String, _ fr: String, _ it: String, _ es: String) -> [String: String] {
        ["de": de, "gsw": gsw, "de-AT": deAT, "en": en, "fr": fr, "it": it, "es": es]
    }

    // In 3 Teile gesplittet: ein einziges Riesen-Literal ließ den Release-Optimizer
    // (Whole-/Per-File) minutenlang kauen. Zusammengeführt beim ersten Zugriff (static let).
    private static let table: [String: [String: String]] =
        _t1.merging(_t2) { a, _ in a }.merging(_t3) { a, _ in a }

    private static let _t1: [String: [String: String]] = [
        "nav.home": r("Home", "Home", "Home", "Home", "Accueil", "Home", "Inicio"),
        "nav.community": r("Community", "Community", "Community", "Community", "Communauté", "Community", "Comunidad"),
        "nav.sessions": r("Sessions", "Sessions", "Sessions", "Sessions", "Sessions", "Sessioni", "Sesiones"),
        "nav.history": r("Verlauf", "Verlauf", "Verlauf", "History", "Historique", "Storico", "Historial"),
        "nav.spots": r("Spots", "Spots", "Spots", "Spots", "Spots", "Spots", "Spots"),
        "nav.chat": r("Chat", "Chat", "Chat", "Chat", "Chat", "Chat", "Chat"),
        "nav.profile": r("Profil", "Profil", "Profil", "Profile", "Profil", "Profilo", "Perfil"),
        "common.save": r("Speichern", "Speichere", "Speichern", "Save", "Enregistrer", "Salva", "Guardar"),
        "common.cancel": r("Abbrechen", "Abbräche", "Abbrechen", "Cancel", "Annuler", "Annulla", "Cancelar"),
        "common.delete": r("Löschen", "Lösche", "Löschen", "Delete", "Supprimer", "Elimina", "Eliminar"),
        "common.saved": r("Gespeichert", "Gspycheret", "Gespeichert", "Saved", "Enregistré", "Salvato", "Guardado"),
        "common.noData": r("Noch keine Daten", "No kei Date", "Noch keine Daten", "No data yet", "Aucune donnée", "Nessun dato", "Sin datos"),
        "common.start": r("Start", "Start", "Start", "Start", "Début", "Inizio", "Inicio"),
        "common.end": r("Ende", "Ändi", "Ende", "End", "Fin", "Fine", "Fin"),

        "login.email": r("E-Mail", "E-Mail", "E-Mail", "Email", "E-mail", "Email", "Correo"),
        "login.password": r("Passwort", "Passwort", "Passwort", "Password", "Mot de passe", "Password", "Contraseña"),
        "login.passwordReg": r("Passwort (min. 8 Zeichen)", "Passwort (min. 8 Zeiche)", "Passwort (min. 8 Zeichen)", "Password (min. 8 chars)", "Mot de passe (8+ car.)", "Password (min. 8)", "Contraseña (mín. 8)"),
        "login.name": r("Anzeigename (optional)", "Aazeigname (optional)", "Anzeigename (optional)", "Display name (optional)", "Nom affiché (optionnel)", "Nome visualizzato (opz.)", "Nombre visible (opcional)"),
        "login.create": r("Konto erstellen", "Konto erstelle", "Konto erstellen", "Create account", "Créer un compte", "Crea account", "Crear cuenta"),
        "login.signin": r("Anmelden", "Aamelde", "Anmelden", "Sign in", "Se connecter", "Accedi", "Iniciar sesión"),
        "login.toRegister": r("Noch kein Konto? Registrieren", "No kes Konto? Registriere", "Noch kein Konto? Registrieren", "No account? Register", "Pas de compte ? S'inscrire", "Nessun account? Registrati", "¿Sin cuenta? Regístrate"),
        "login.toLogin": r("Schon ein Konto? Anmelden", "Scho es Konto? Aamelde", "Schon ein Konto? Anmelden", "Have an account? Sign in", "Déjà un compte ? Se connecter", "Hai un account? Accedi", "¿Ya tienes cuenta? Inicia sesión"),
        "login.or": r("oder", "oder", "oder", "or", "ou", "o", "o"),
        "login.google": r("Mit Google anmelden", "Mit Google aamelde", "Mit Google anmelden", "Sign in with Google", "Se connecter avec Google", "Accedi con Google", "Iniciar sesión con Google"),

        "profile.foils": r("Foils", "Foils", "Foils", "Foils", "Foils", "Foils", "Foils"),
        "profile.foilsSub": r("Katalog · meine & Standard", "Katalog · myni & Standard", "Katalog · meine & Standard", "Catalog · mine & default", "Catalogue · les miens & défaut", "Catalogo · i miei & predefinito", "Catálogo · míos & predet."),
        "profile.calc": r("Foil-Rechner", "Foil-Rächner", "Foil-Rechner", "Foil calculator", "Calculateur de foil", "Calcolatore foil", "Calculadora de foil"),
        "profile.calcSub": r("Foils vergleichen & Pump-Leistung", "Foils vergliiche & Pump-Leischtig", "Foils vergleichen & Pump-Leistung", "Compare foils & pump power", "Comparer foils & puissance", "Confronta foil & potenza", "Comparar foils & potencia"),
        "profile.stats": r("Foil-Statistik", "Foil-Statistik", "Foil-Statistik", "Foil stats", "Stats de foil", "Statistiche foil", "Estadísticas de foil"),
        "profile.statsSub": r("Community: Werte je Foil", "Community: Wärt pro Foil", "Community: Werte je Foil", "Community: values per foil", "Communauté : valeurs par foil", "Community: valori per foil", "Comunidad: valores por foil"),
        "profile.alarm": r("On-Foil Alarm", "On-Foil Alarm", "On-Foil Alarm", "On-foil alarm", "Alarme on-foil", "Allarme on-foil", "Alarma on-foil"),
        "profile.alarmSub": r("Speed-Grenzen & Muster für die Uhr", "Speed-Gränze & Muschter für d Uhr", "Speed-Grenzen & Muster für die Uhr", "Speed limits & patterns for the watch", "Limites de vitesse & motifs", "Limiti di velocità & schemi", "Límites de velocidad & patrones"),
        "profile.datafields": r("Datenseiten", "Datesyte", "Datenseiten", "Data screens", "Écrans de données", "Schermate dati", "Pantallas de datos"),
        "profile.datafieldsSub": r("Felder je Uhr-Screen konfigurieren", "Fälder pro Uhr-Screen", "Felder je Uhr-Screen konfigurieren", "Configure fields per watch screen", "Champs par écran de montre", "Campi per schermata", "Campos por pantalla"),
        "profile.compare": r("Sessions vergleichen", "Sessions vergliiche", "Sessions vergleichen", "Compare sessions", "Comparer les sessions", "Confronta sessioni", "Comparar sesiones"),
        "profile.compareSub": r("Kennzahlen mehrerer Sessions", "Kennzahle vo mehrere Sessions", "Kennzahlen mehrerer Sessions", "Metrics of multiple sessions", "Mesures de plusieurs sessions", "Metriche di più sessioni", "Métricas de varias sesiones"),
        "profile.logout": r("Abmelden", "Abmälde", "Abmelden", "Sign out", "Se déconnecter", "Esci", "Cerrar sesión"),
        "profile.deleteAccount": r("Konto löschen", "Konto lösche", "Konto löschen", "Delete account", "Supprimer le compte", "Elimina account", "Eliminar cuenta"),
        "profile.deleteConfirm": r("Konto wirklich löschen? Alle deine Daten (Sessions, Fotos, Profil) werden unwiderruflich gelöscht.", "Konto würkli lösche? Alli dini Date (Sessions, Fotos, Profil) werded unwiderrueflich glöscht.", "Konto wirklich löschen? Olle deine Daten (Sessions, Fotos, Profil) werdn unwiderruflich glöscht.", "Delete your account? All your data (sessions, photos, profile) will be permanently deleted.", "Supprimer le compte ? Toutes tes données (sessions, photos, profil) seront définitivement supprimées.", "Eliminare l'account? Tutti i tuoi dati (sessioni, foto, profilo) verranno eliminati definitivamente.", "¿Eliminar la cuenta? Todos tus datos (sesiones, fotos, perfil) se eliminarán de forma permanente."),
        "profile.deleteConfirmBtn": r("Endgültig löschen", "Entgültig lösche", "Endgültig löschen", "Delete permanently", "Supprimer définitivement", "Elimina definitivamente", "Eliminar permanentemente"),
        "profile.editName": r("Anzeigename", "Aazeigname", "Anzeigename", "Display name", "Nom affiché", "Nome visualizzato", "Nombre visible"),
        "profile.web": r("pumpfoil.org öffnen", "pumpfoil.org öffne", "pumpfoil.org öffnen", "Open pumpfoil.org", "Ouvrir pumpfoil.org", "Apri pumpfoil.org", "Abrir pumpfoil.org"),

        "settings.title": r("Einstellungen", "Yystellige", "Einstellungen", "Settings", "Réglages", "Impostazioni", "Ajustes"),
        "settings.weight": r("Gewicht", "Gwicht", "Gewicht", "Weight", "Poids", "Peso", "Peso"),
        "settings.homespot": r("Homespot", "Homespot", "Homespot", "Home spot", "Spot principal", "Spot principale", "Spot principal"),
        "settings.auto": r("Automatisch", "Automatisch", "Automatisch", "Automatic", "Automatique", "Automatico", "Automático"),
        "settings.design": r("Design", "Design", "Design", "Theme", "Thème", "Tema", "Tema"),
        "settings.language": r("Sprache", "Sprooch", "Sprache", "Language", "Langue", "Lingua", "Idioma"),
        "settings.light": r("Hell", "Häll", "Hell", "Light", "Clair", "Chiaro", "Claro"),
        "settings.dark": r("Dunkel", "Dunkel", "Dunkel", "Dark", "Sombre", "Scuro", "Oscuro"),
        "settings.notifications": r("Benachrichtigungen", "Benachrichtigunge", "Benachrichtigungen", "Notifications", "Notifications", "Notifiche", "Notificaciones"),
        "settings.nLikes": r("Likes", "Likes", "Likes", "Likes", "J'aime", "Mi piace", "Me gusta"),
        "settings.nAnalyzed": r("Auswertung fertig", "Uuswertig fertig", "Auswertung fertig", "Analysis ready", "Analyse prête", "Analisi pronta", "Análisis listo"),
        "settings.nRecord": r("Aufnahme/Records", "Ufnahm/Records", "Aufnahme/Records", "Recording/records", "Enreg./records", "Registrazione/record", "Grabación/récords"),

        "home.hello": r("Hallo", "Hoi", "Servus", "Hi", "Salut", "Ciao", "Hola"),
        "home.weather": r("Wetter am Homespot", "Wätter am Homespot", "Wetter am Homespot", "Weather at home spot", "Météo au spot", "Meteo allo spot", "Tiempo en el spot"),
        "home.myChats": r("Meine Chats", "Mini Chats", "Meine Chats", "My chats", "Mes chats", "Le mie chat", "Mis chats"),
        "wx.today": r("Heute", "Hüt", "Heute", "Today", "Auj.", "Oggi", "Hoy"),
        "wx.tomorrow": r("Morgen", "Morn", "Morgen", "Tomorrow", "Demain", "Domani", "Mañana"),
        "home.foiling": r("Foiling", "Foiling", "Foiling", "Foiling", "Foiling", "Foiling", "Foiling"),
        "home.runs": r("Läufe", "Läuf", "Läufe", "Runs", "Runs", "Run", "Tramos"),
        "home.pumps": r("Pumps", "Pumps", "Pumps", "Pumps", "Pumps", "Pumps", "Pumps"),
        "home.records": r("Rekorde", "Rekord", "Rekorde", "Records", "Records", "Record", "Récords"),
        "home.topSpeed": r("Top-Speed", "Top-Speed", "Top-Speed", "Top speed", "Vitesse max", "Velocità max", "Velocidad máx"),
        "home.farthestRun": r("Weitester Lauf", "Wytischte Lauf", "Weitester Lauf", "Farthest run", "Plus longue distance", "Distanza max", "Distancia máx"),
        "home.longestRun": r("Längster Lauf", "Längschte Lauf", "Längster Lauf", "Longest run", "Plus longue durée", "Durata max", "Duración máx"),
        "home.longestGlide": r("Längster Gleit", "Längschte Gleit", "Längster Gleit", "Longest glide", "Plus long plané", "Planata max", "Planeo máx"),
        "home.mostRuns": r("Meiste Läufe", "Meischti Läuf", "Meiste Läufe", "Most runs", "Plus de runs", "Più run", "Más tramos"),
        "home.latest": r("Letzte Sessions", "Letschti Sessions", "Letzte Sessions", "Latest sessions", "Dernières sessions", "Ultime sessioni", "Últimas sesiones"),

        "sessions.mine": r("Meine", "Myni", "Meine", "Mine", "Les miennes", "Le mie", "Mías"),
        "sessions.all": r("Alle", "Alli", "Alle", "All", "Toutes", "Tutte", "Todas"),
        "sessions.searchSpot": r("Spot suchen", "Spot sueche", "Spot suchen", "Search spot", "Chercher un spot", "Cerca spot", "Buscar spot"),
        "sessions.empty": r("Keine Sessions", "Kei Sessions", "Keine Sessions", "No sessions", "Aucune session", "Nessuna sessione", "Sin sesiones"),

        "verlauf.empty": r("Noch keine Auswertungen", "No kei Uuswertige", "Noch keine Auswertungen", "No analyses yet", "Aucune analyse", "Nessuna analisi", "Sin análisis"),
        "verlauf.total": r("Gesamt", "Gsamt", "Gesamt", "Total", "Total", "Totale", "Total"),
    ]

    private static let _t2: [String: [String: String]] = [
        "verlauf.cumulative": r("Kumuliert", "Kumuliert", "Kumuliert", "Cumulative", "Cumulé", "Cumulato", "Acumulado"),
        "verlauf.daysWord": r("Tage", "Täg", "Tage", "days", "jours", "giorni", "días"),
        "verlauf.daysAbbr": r("T", "T", "T", "d", "j", "g", "d"),
        "verlauf.period": r("Zeitraum", "Ziitruum", "Zeitraum", "Period", "Période", "Periodo", "Periodo"),
        "verlauf.kmFoiling": r("km Foiling", "km Foiling", "km Foiling", "km foiling", "km foiling", "km foiling", "km foiling"),
        "verlauf.foilingPerSession": r("Foiling/Session", "Foiling/Session", "Foiling/Session", "Foiling/session", "Foiling/session", "Foiling/sessione", "Foiling/sesión"),
        "verlauf.pumpsPerSession": r("Pumps/Session", "Pumps/Session", "Pumps/Session", "Pumps/session", "Pumps/session", "Pump/sessione", "Pumps/sesión"),
        "verlauf.aggTitle": r("Summen & Schnitte", "Summe & Schnitt", "Summen & Schnitte", "Totals & averages", "Totaux & moyennes", "Totali & medie", "Totales y medias"),
        "sd.avgSpeed": r("Ø Geschwindigkeit", "Ø Gschwindigkeit", "Ø Geschwindigkeit", "Avg speed", "Vitesse moy.", "Velocità media", "Velocidad media"),
        "sd.avgPump": r("Ø Pump-Frequenz", "Ø Pump-Frequänz", "Ø Pump-Frequenz", "Avg pump rate", "Cadence moy.", "Cadenza media", "Cadencia media"),
        "sd.avgDistPerPump": r("Ø Strecke/Pump", "Ø Strecki/Pump", "Ø Strecke/Pump", "Avg dist/pump", "Dist. moy./pump", "Dist. media/pump", "Dist. media/pump"),
        "sd.avgHr": r("Ø Puls", "Ø Puls", "Ø Puls", "Avg HR", "FC moy.", "FC media", "FC media"),
        "sd.maxHr": r("Max Puls", "Max Puls", "Max Puls", "Max HR", "FC max.", "FC max", "FC máx"),
        "sd.clearSelection": r("Auswahl aufheben", "Uuswahl ufhebe", "Auswahl aufheben", "Clear selection", "Effacer", "Deseleziona", "Quitar selección"),
        "community.leaderboard": r("Bestenliste", "Bestelischte", "Bestenliste", "Leaderboard", "Classement", "Classifica", "Clasificación"),
        "community.latestMedia": r("Neueste Medien", "Nöischti Medie", "Neueste Medien", "Latest media", "Médias récents", "Media recenti", "Medios recientes"),
        "community.topRated": r("Best bewertet", "Bescht bewärtet", "Best bewertet", "Top rated", "Mieux notés", "Più apprezzati", "Mejor valorados"),
        "community.spotRecords": r("Rekorde an einem Spot", "Rekord an eme Spot", "Rekorde an einem Spot", "Records at a spot", "Records sur un spot", "Record di uno spot", "Récords de un spot"),
        "watch.title": r("Apple Watch", "Apple Watch", "Apple Watch", "Apple Watch", "Apple Watch", "Apple Watch", "Apple Watch"),
        "watch.ok": r("App installiert · Updates kommen automatisch mit der iPhone-App.", "App installiert · Updates chömed automatisch mit de iPhone-App.", "App installiert · Updates kommen automatisch mit der iPhone-App.", "App installed · updates come automatically with the iPhone app.", "App installée · mises à jour auto avec l'app iPhone.", "App installata · aggiornamenti automatici con l'app iPhone.", "App instalada · actualizaciones automáticas con la app de iPhone."),
        "watch.notInstalled": r("Uhr gekoppelt, App fehlt — in der Watch-App auf dem iPhone unter „Verfügbare Apps“ hinzufügen.", "Uhr kopplet, App fählt — i de Watch-App ufem iPhone under „Verfügbari Apps“ zuefüege.", "Uhr gekoppelt, App fehlt — in der Watch-App am iPhone unter „Verfügbare Apps“ hinzufügen.", "Watch paired, app missing — add it in the Watch app on iPhone under “Available Apps”.", "Montre liée, app absente — ajoutez-la dans l'app Watch (iPhone), « Apps disponibles ».", "Orologio accoppiato, app assente — aggiungila nell'app Watch su iPhone in “App disponibili”.", "Reloj emparejado, falta la app — añádela en la app Watch del iPhone en «Apps disponibles»."),
        "watch.none": r("Keine Apple Watch gekoppelt.", "Kei Apple Watch kopplet.", "Keine Apple Watch gekoppelt.", "No Apple Watch paired.", "Aucune Apple Watch liée.", "Nessuna Apple Watch accoppiata.", "Ningún Apple Watch emparejado."),

        "spots.empty": r("Noch keine Spots", "No kei Spots", "Noch keine Spots", "No spots yet", "Aucun spot", "Nessuno spot", "Sin spots"),
        "chat.empty": r("Noch keine Chats", "No kei Chats", "Noch keine Chats", "No chats yet", "Aucun chat", "Nessuna chat", "Sin chats"),
        "chat.placeholder": r("Nachricht", "Nachricht", "Nachricht", "Message", "Message", "Messaggio", "Mensaje"),
        "chat.send": r("Senden", "Schicke", "Senden", "Send", "Envoyer", "Invia", "Enviar"),

        "foils.search": r("Foil suchen", "Foil sueche", "Foil suchen", "Search foil", "Chercher un foil", "Cerca foil", "Buscar foil"),
        "foils.brand": r("Marke", "Marke", "Marke", "Brand", "Marque", "Marca", "Marca"),
        "foils.mine": r("Meine Foils", "Myni Foils", "Meine Foils", "My foils", "Mes foils", "I miei foil", "Mis foils"),
        "foils.all": r("Alle Foils", "Alli Foils", "Alle Foils", "All foils", "Tous les foils", "Tutti i foil", "Todos los foils"),
        "foils.more": r("Weitere", "Wytri", "Weitere", "More", "Autres", "Altri", "Más"),
        "foils.default": r("Standard", "Standard", "Standard", "Default", "Défaut", "Predefinito", "Predet."),

        "foilstats.intro": r("Welche Werte mit welchem Foil gefahren werden (Community).", "Weli Wärt mit welem Foil gfahre wärde (Community).", "Welche Werte mit welchem Foil gefahren werden (Community).", "Which values are ridden with which foil (community).", "Quelles valeurs avec quel foil (communauté).", "Quali valori con quale foil (community).", "Qué valores con qué foil (comunidad)."),
        "foilstats.riders": r("Fahrer", "Fahrer", "Fahrer", "Riders", "Riders", "Rider", "Riders"),
        "foilstats.bestKm": r("best km", "best km", "best km", "best km", "meilleur km", "miglior km", "mejor km"),

        "datafields.intro": r("Bis zu 3 Felder pro Seite. Leere Seiten entfallen auf der Uhr.", "Bis zu 3 Fälder pro Syte. Lääri Syte falle uf de Uhr wäg.", "Bis zu 3 Felder pro Seite. Leere Seiten entfallen auf der Uhr.", "Up to 3 fields per page. Empty pages are skipped on the watch.", "Jusqu'à 3 champs par page. Les pages vides sont ignorées sur la montre.", "Fino a 3 campi per pagina. Le pagine vuote vengono saltate sull'orologio.", "Hasta 3 campos por página. Las páginas vacías se omiten en el reloj."),
        "datafields.page": r("Seite", "Syte", "Seite", "Page", "Page", "Pagina", "Página"),
        "datafields.field": r("Feld", "Fäld", "Feld", "Field", "Champ", "Campo", "Campo"),
        "datafields.removePage": r("Seite entfernen", "Syte entferne", "Seite entfernen", "Remove page", "Supprimer la page", "Rimuovi pagina", "Quitar página"),
        "datafields.addPage": r("Seite hinzufügen", "Syte zuefüege", "Seite hinzufügen", "Add page", "Ajouter une page", "Aggiungi pagina", "Añadir página"),

        "field.0": r("— leer —", "— läär —", "— leer —", "— off —", "— vide —", "— vuoto —", "— vacío —"),
        "field.1": r("Speed (3 s)", "Speed (3 s)", "Speed (3 s)", "Speed (3 s)", "Vitesse (3 s)", "Velocità (3 s)", "Velocidad (3 s)"),
        "field.5": r("Speed (aktuell)", "Speed (aktuell)", "Speed (aktuell)", "Speed (current)", "Vitesse (actuelle)", "Velocità (attuale)", "Velocidad (actual)"),
        "field.6": r("Ø Speed", "Ø Speed", "Ø Speed", "Avg speed", "Vitesse moy.", "Velocità media", "Velocidad med."),
        "field.7": r("Max Speed", "Max Speed", "Max Speed", "Max speed", "Vitesse max", "Velocità max", "Velocidad máx"),
        "field.2": r("Puls", "Puls", "Puls", "Heart rate", "Fréq. cardiaque", "Frequenza card.", "Pulso"),
        "field.8": r("Ø Puls", "Ø Puls", "Ø Puls", "Avg HR", "FC moy.", "FC media", "Pulso med."),
        "field.9": r("Max Puls", "Max Puls", "Max Puls", "Max HR", "FC max", "FC max", "Pulso máx"),
        "field.3": r("Zeit", "Ziit", "Zeit", "Time", "Temps", "Tempo", "Tiempo"),
        "field.4": r("Distanz", "Distanz", "Distanz", "Distance", "Distance", "Distanza", "Distancia"),
        "field.10": r("Höhe", "Höchi", "Höhe", "Altitude", "Altitude", "Altitudine", "Altitud"),
        "field.13": r("Aufstieg", "Ufstig", "Aufstieg", "Ascent", "Montée", "Salita", "Ascenso"),
        "field.11": r("Temperatur", "Temperatur", "Temperatur", "Temperature", "Température", "Temperatura", "Temperatura"),
        "field.12": r("Uhrzeit", "Uhrziit", "Uhrzeit", "Clock", "Heure", "Ora", "Hora"),
        "field.14": r("Lauf Dauer (live)", "Lauf Duur (live)", "Lauf Dauer (live)", "Run duration (live)", "Durée run (live)", "Durata run (live)", "Duración run (vivo)"),
        "field.15": r("Lauf Strecke (live)", "Lauf Strecki (live)", "Lauf Strecke (live)", "Run distance (live)", "Distance run (live)", "Distanza run (live)", "Distancia run (vivo)"),
        "field.16": r("Letzter Lauf: Dauer", "Letschte Lauf: Duur", "Letzter Lauf: Dauer", "Last run: duration", "Dernier run : durée", "Ultimo run: durata", "Último run: duración"),
        "field.17": r("Letzter Lauf: Strecke", "Letschte Lauf: Strecki", "Letzter Lauf: Strecke", "Last run: distance", "Dernier run : distance", "Ultimo run: distanza", "Último run: distancia"),
        "field.18": r("Letzter Lauf: Ø Speed", "Letschte Lauf: Ø Speed", "Letzter Lauf: Ø Speed", "Last run: avg speed", "Dernier run : vit. moy.", "Ultimo run: vel. media", "Último run: vel. med."),
        "field.19": r("Letzter Lauf: Max Speed", "Letschte Lauf: Max Speed", "Letzter Lauf: Max Speed", "Last run: max speed", "Dernier run : vit. max", "Ultimo run: vel. max", "Último run: vel. máx"),
        "field.20": r("Läufe (Anzahl)", "Läuf (Aazahl)", "Läufe (Anzahl)", "Runs (count)", "Runs (nombre)", "Run (numero)", "Runs (número)"),

        "alarm.title": r("Vibrationsalarm", "Vibrationsalarm", "Vibrationsalarm", "Vibration alarm", "Alarme vibrante", "Allarme a vibrazione", "Alarma por vibración"),
        "alarm.desc": r("Die Uhr vibriert beim Foilen, sobald du eine Geschwindigkeitsgrenze über- oder unterschreitest – z. B. um in der optimalen Pump-Geschwindigkeit zu bleiben. Ist der Alarm aus, zeigt der Uhr-Startbildschirm „Alarm: aus“.", "D Uhr vibriert bim Foile, sobald d über oder under e Gschwindigkeitsgränze chunnsch – z. B. zum i de optimale Pump-Gschwindigkeit blibe. Wenn de Alarm us isch, zeigt de Uhr-Startbildschirm „Alarm: us“.", "Die Uhr vibriert beim Foilen, sobald du eine Geschwindigkeitsgrenze über- oder unterschreitest – z. B. um in der optimalen Pump-Geschwindigkeit zu bleiben. Ist der Alarm aus, zeigt der Uhr-Startbildschirm „Alarm: aus“.", "The watch vibrates while foiling when you cross a speed threshold – e.g. to stay in the optimal pump speed. When the alarm is off, the watch start screen shows “Alarm: off”.", "La montre vibre pendant le foil quand tu franchis un seuil de vitesse, p. ex. pour rester à la vitesse de pompage optimale. Si l'alarme est désactivée, l'écran d'accueil de la montre affiche « Alarme : off ».", "L'orologio vibra durante il foiling quando superi una soglia di velocità, ad es. per restare alla velocità di pompaggio ottimale. Se l'allarme è disattivato, la schermata iniziale dell'orologio mostra «Allarme: off».", "El reloj vibra mientras foileas cuando cruzas un umbral de velocidad, p. ej. para mantenerte en la velocidad óptima de bombeo. Si la alarma está desactivada, la pantalla de inicio del reloj muestra «Alarma: off»."),
        "alarm.enable": r("Vibrationsalarm aktivieren", "Vibrationsalarm aktiviere", "Vibrationsalarm aktivieren", "Enable vibration alarm", "Activer l'alarme vibrante", "Attiva l'allarme a vibrazione", "Activar alarma por vibración"),
        "alarm.defaultSource": r("Standard auf der Uhr", "Standard uf de Uhr", "Standard auf der Uhr", "Default on the watch", "Par défaut sur la montre", "Predefinito sull'orologio", "Predeterminado en el reloj"),
        "alarm.defaultFoil": r("Mein Standard-Foil", "Mis Standard-Foil", "Mein Standard-Foil", "My default foil", "Mon foil par défaut", "Il mio foil predefinito", "Mi foil predeterminado"),
        "alarm.defaultFixed": r("Feste Werte (unten)", "Feschti Wärt (unde)", "Feste Werte (unten)", "Fixed values (below)", "Valeurs fixes (ci-dessous)", "Valori fissi (sotto)", "Valores fijos (abajo)"),
        "alarm.defaultHelp": r("Womit die Uhr beim Start vorbelegt ist – an der Uhr (↓) jederzeit umstellbar. „Mein Standard-Foil“ nutzt die aus Foil + Gewicht berechneten Schwellen, „Feste Werte“ die unten eingestellten.", "Womit d Uhr bim Start vorbeleit isch – uf de Uhr (↓) jederziit umstellbar. „Mis Standard-Foil“ nimmt di us Foil + Gwicht berächnete Schwelle, „Feschti Wärt“ di unde igstellte.", "Womit die Uhr beim Start vorbelegt ist – an der Uhr (↓) jederzeit umstellbar. „Mein Standard-Foil“ nutzt die aus Foil + Gewicht berechneten Schwellen, „Feste Werte“ die unten eingestellten.", "What the watch preselects at start – changeable on the watch (↓) any time. “My default foil” uses the thresholds derived from foil + weight, “Fixed values” the ones set below.", "Ce que la montre présélectionne au démarrage, modifiable sur la montre (↓) à tout moment. « Mon foil par défaut » utilise les seuils calculés à partir du foil et du poids, « Valeurs fixes » celles définies ci-dessous.", "Ciò che l'orologio preseleziona all'avvio, modificabile sull'orologio (↓) in qualsiasi momento. «Il mio foil predefinito» usa le soglie calcolate da foil + peso, «Valori fissi» quelle impostate sotto.", "Lo que el reloj preselecciona al iniciar, modificable en el reloj (↓) en cualquier momento. «Mi foil predeterminado» usa los umbrales calculados a partir del foil y el peso; «Valores fijos», los configurados abajo."),
        "alarm.overTitle": r("Max-Geschwindigkeit überschritten", "Über de Max-Gschwindigkeit", "Max-Geschwindigkeit überschritten", "Above max speed", "Au-dessus de la vitesse max", "Sopra la velocità max", "Por encima de la velocidad máx"),
        "alarm.underTitle": r("Min-Geschwindigkeit unterschritten", "Under de Min-Gschwindigkeit", "Min-Geschwindigkeit unterschritten", "Below min speed", "En dessous de la vitesse min", "Sotto la velocità min", "Por debajo de la velocidad mín"),
        "alarm.maxSpeed": r("Max", "Max", "Max", "Max", "Max", "Max", "Máx"),
        "alarm.minSpeed": r("Min", "Min", "Min", "Min", "Min", "Min", "Mín"),
    ]

    private static let _t3: [String: [String: String]] = [
        "alarm.pattern": r("Muster", "Muster", "Muster", "Pattern", "Motif", "Schema", "Patrón"),
        "alarm.mode": r("Auslösen", "Uslöse", "Auslösen", "Trigger", "Déclenchement", "Attivazione", "Activación"),
        "alarm.modeOnce": r("einmalig beim Über-/Unterschreiten", "eimal bim Über-/Underschriite", "einmalig beim Über-/Unterschreiten", "once when crossing", "une fois au franchissement", "una volta al superamento", "una vez al cruzar"),
        "alarm.modeContinuous": r("dauerhaft, solange drüber/drunter", "dauerhaft, solang drüber/drunter", "dauerhaft, solange drüber/drunter", "continuously while above/below", "en continu tant que dépassé", "in continuo finché sopra/sotto", "continuo mientras esté por encima/debajo"),
        "alarm.zeroHint": r("Tipp: 0 km/h schaltet die jeweilige Grenze aus.", "Tipp: 0 km/h schaltet die Gränze us.", "Tipp: 0 km/h schaltet die jeweilige Grenze aus.", "Tip: 0 km/h disables that threshold.", "Astuce : 0 km/h désactive ce seuil.", "Suggerimento: 0 km/h disattiva quella soglia.", "Consejo: 0 km/h desactiva ese umbral."),
        "alarm.patShort1": r("1× kurz", "1× churz", "1× kurz", "1× short", "1× court", "1× breve", "1× corto"),
        "alarm.patShort2": r("2× kurz", "2× churz", "2× kurz", "2× short", "2× court", "2× breve", "2× corto"),
        "alarm.patLong2": r("2× lang", "2× lang", "2× lang", "2× long", "2× long", "2× lungo", "2× largo"),
        "alarm.patLsl": r("lang-kurz-lang", "lang-churz-lang", "lang-kurz-lang", "long-short-long", "long-court-long", "lungo-breve-lungo", "largo-corto-largo"),

        "compare.title": r("Vergleichen", "Vergliiche", "Vergleichen", "Compare", "Comparer", "Confronta", "Comparar"),
        "compare.result": r("Vergleich", "Vergliich", "Vergleich", "Comparison", "Comparaison", "Confronto", "Comparación"),
        "compare.pick": r("2+ Sessions zum Vergleich wählen", "2+ Sessions zum Vergliiche wähle", "2+ Sessions zum Vergleich wählen", "Select 2+ sessions to compare", "Sélectionner 2+ sessions à comparer", "Seleziona 2+ sessioni da confrontare", "Selecciona 2+ sesiones para comparar"),
        "compare.backToSelection": r("Auswahl", "Uswahl", "Auswahl", "Selection", "Sélection", "Selezione", "Selección"),
        "compare.distance": r("Strecke", "Strecki", "Strecke", "Distance", "Distance", "Distanza", "Distancia"),
        "compare.foilTime": r("Foil-Zeit", "Foil-Ziit", "Foil-Zeit", "Foil time", "Temps foil", "Tempo foil", "Tiempo foil"),
        "compare.cadence": r("Cadence", "Cadence", "Cadence", "Cadence", "Cadence", "Cadenza", "Cadencia"),

        "lab.title": r("Labeln", "Labele", "Labeln", "Label", "Étiqueter", "Etichetta", "Etiquetar"),
        "lab.pump": r("Pumpen", "Pumpe", "Pumpen", "Pumping", "Pump", "Pump", "Pump"),
        "lab.glide": r("Gleiten", "Gleite", "Gleiten", "Gliding", "Glisse", "Planata", "Planeo"),
        "lab.notFoiling": r("kein Foilen", "kei Foile", "kein Foilen", "not foiling", "pas de foil", "niente foil", "sin foil"),
        "lab.existing": r("Vorhandene Labels", "Vorhandeni Labels", "Vorhandene Labels", "Existing labels", "Labels existants", "Etichette esistenti", "Etiquetas existentes"),
        "lab.add": r("Label hinzufügen", "Label zuefüege", "Label hinzufügen", "Add label", "Ajouter un label", "Aggiungi etichetta", "Añadir etiqueta"),
        "lab.type": r("Typ", "Typ", "Typ", "Type", "Type", "Tipo", "Tipo"),
        "lab.introShort": r("Bereiche markieren (Trainingsdaten fürs Modell).", "Beriich markiere (Trainingsdate fürs Modäll).", "Bereiche markieren (Trainingsdaten fürs Modell).", "Mark ranges (training data for the model).", "Marquer des plages (données d'entraînement pour le modèle).", "Segna intervalli (dati di addestramento per il modello).", "Marca rangos (datos de entrenamiento del modelo)."),

        "records.today": r("Heute", "Hüt", "Heute", "Today", "Aujourd'hui", "Oggi", "Hoy"),
        "records.year": r("Jahr", "Jahr", "Jahr", "Year", "Année", "Anno", "Año"),
        "records.empty": r("Noch keine Rekorde in diesem Zeitraum.", "No kei Rekord i dem Ziitruum.", "Noch keine Rekorde in diesem Zeitraum.", "No records in this period yet.", "Aucun record sur cette période.", "Nessun record in questo periodo.", "Sin récords en este periodo."),

        "calc.intro": r("Vergleiche Foils: Basis-Kennwerte und theoretische Leistung über die Geschwindigkeit.", "Vergliich Foils: Basis-Wärt und theoretischi Leischtig über d Gschwindigkeit.", "Vergleiche Foils: Basis-Kennwerte und theoretische Leistung über die Geschwindigkeit.", "Compare foils: basic characteristics and theoretical power across speed.", "Comparez les foils : caractéristiques de base et puissance théorique selon la vitesse.", "Confronta i foil: caratteristiche di base e potenza teorica al variare della velocità.", "Compara foils: características básicas y potencia teórica según la velocidad."),
        "calc.params": r("Parameter", "Parameter", "Parameter", "Parameters", "Paramètres", "Parametri", "Parámetros"),
        "calc.equip": r("Equip. (kg)", "Equip. (kg)", "Equip. (kg)", "Equip. (kg)", "Équip. (kg)", "Equip. (kg)", "Equipo (kg)"),
        "calc.mastDiameter": r("Mast-Ø", "Mast-Ø", "Mast-Ø", "Mast Ø", "Mât Ø", "Albero Ø", "Mástil Ø"),
        "calc.mastDepth": r("Mast-Tiefe", "Mast-Tüfi", "Mast-Tiefe", "Mast depth", "Profondeur du mât", "Profondità albero", "Profundidad del mástil"),
        "calc.withPump": r("Mit Pump-Inertia", "Mit Pump-Inertia", "Mit Pump-Inertia", "With pump inertia", "Avec inertie de pump", "Con inerzia di pump", "Con inercia de pump"),
        "calc.freq": r("Freq. (Hz)", "Freq. (Hz)", "Freq. (Hz)", "Freq. (Hz)", "Fréq. (Hz)", "Freq. (Hz)", "Frec. (Hz)"),
        "calc.heave": r("Hub (cm)", "Hub (cm)", "Hub (cm)", "Heave (cm)", "Ampl. (cm)", "Corsa (cm)", "Carrera (cm)"),
        "calc.loss": r("Verlust %", "Verluscht %", "Verlust %", "Loss %", "Perte %", "Perdita %", "Pérdida %"),
        "calc.equipment": r("Equipment", "Equipment", "Equipment", "Equipment", "Équipement", "Attrezzatura", "Equipo"),
        "calc.frequency": r("Frequenz", "Frequänz", "Frequenz", "Frequency", "Fréquence", "Frequenza", "Frecuencia"),
        "calc.heaveWord": r("Hub", "Hub", "Hub", "Heave", "Amplitude", "Corsa", "Carrera"),
        "calc.lossWord": r("Verlust", "Verluscht", "Verlust", "Loss", "Perte", "Perdita", "Pérdida"),

        "sd.title": r("Session", "Session", "Session", "Session", "Session", "Sessione", "Sesión"),
        "sd.deleteTitle": r("Session löschen?", "Session lösche?", "Session löschen?", "Delete session?", "Supprimer la session ?", "Eliminare la sessione?", "¿Eliminar sesión?"),
        "sd.deleteBody": r("Diese Session wird ausgeblendet und aus der Community entfernt.", "Die Session wird usgblendet und us de Community entfernt.", "Diese Session wird ausgeblendet und aus der Community entfernt.", "This session will be hidden and removed from the community.", "Cette session sera masquée et retirée de la communauté.", "Questa sessione verrà nascosta e rimossa dalla community.", "Esta sesión se ocultará y se quitará de la comunidad."),
        "sd.trim": r("Zuschneiden", "Zueschniide", "Zuschneiden", "Trim", "Rogner", "Ritaglia", "Recortar"),
        "sd.trimReset": r("Zuschnitt aufheben", "Zueschnitt ufhebe", "Zuschnitt aufheben", "Clear trim", "Annuler le rognage", "Annulla ritaglio", "Quitar recorte"),
        "sd.apply": r("Anwenden", "Aawände", "Anwenden", "Apply", "Appliquer", "Applica", "Aplicar"),
        "sd.report": r("Melden", "Mälde", "Melden", "Report", "Signaler", "Segnala", "Reportar"),
        "sd.reportFake": r("Als Fake melden", "Als Fake mälde", "Als Fake melden", "Report as fake", "Signaler comme faux", "Segnala come falso", "Reportar como falso"),
        "sd.reportInappropriate": r("Als unangemessen melden", "Als unaagmässe mälde", "Als unangemessen melden", "Report as inappropriate", "Signaler comme inapproprié", "Segnala come inappropriato", "Reportar como inapropiado"),
        "sd.caption": r("Beschriftung", "Beschriftig", "Beschriftung", "Caption", "Légende", "Didascalia", "Título"),
        "sd.captionAdd": r("Beschriftung hinzufügen", "Beschriftig zuefüege", "Beschriftung hinzufügen", "Add caption", "Ajouter une légende", "Aggiungi didascalia", "Añadir título"),
        "sd.captionEdit": r("Beschriftung bearbeiten", "Beschriftig bearbeite", "Beschriftung bearbeiten", "Edit caption", "Modifier la légende", "Modifica didascalia", "Editar título"),
        "sd.addPhoto": r("Foto hinzufügen", "Foto zuefüege", "Foto hinzufügen", "Add photo", "Ajouter une photo", "Aggiungi foto", "Añadir foto"),
        "sd.colorSpeed": r("Speed", "Speed", "Speed", "Speed", "Vitesse", "Velocità", "Velocidad"),
        "sd.colorPuls": r("Puls", "Puls", "Puls", "Pulse", "Pouls", "Battito", "Pulso"),
        "sd.colorPump": r("Pump", "Pump", "Pump", "Pump", "Pump", "Pump", "Pump"),
        "sd.pumpMarker": r("Pump-Marker", "Pump-Marker", "Pump-Marker", "Pump markers", "Marqueurs de pump", "Marcatori pump", "Marcadores de pump"),
        "sd.foilOfSession": r("Foil dieser Session", "Foil vo dere Session", "Foil dieser Session", "Foil for this session", "Foil de cette session", "Foil di questa sessione", "Foil de esta sesión"),
        "sd.analyzing": r("Auswertung läuft noch …", "Uuswertig lauft no …", "Auswertung läuft noch …", "Analysis still running …", "Analyse en cours …", "Analisi in corso …", "Análisis en curso …"),
        "sd.power": r("Leistung", "Leischtig", "Leistung", "Power", "Puissance", "Potenza", "Potencia"),
        "sd.atAvg": r("bei Ø-Speed", "bi Ø-Speed", "bei Ø-Speed", "at avg speed", "à vit. moy.", "a vel. media", "a vel. med."),
        "sd.atTop": r("bei Top-Speed", "bi Top-Speed", "bei Top-Speed", "at top speed", "à vit. max", "a vel. max", "a vel. máx"),
        "sd.hDist": r("Dist", "Dist", "Dist", "Dist", "Dist", "Dist", "Dist"),
        "sd.coloring": r("Färbung", "Färbig", "Färbung", "Coloring", "Coloration", "Colorazione", "Coloración"),
        "sd.smoothing": r("Glättung", "Glättig", "Glättung", "Smoothing", "Lissage", "Smoothing", "Suavizado"),
        "calc.pickHint": r("Foils auswählen, um Kennwerte zu vergleichen.", "Foils uuswähle, zum Kennwärt vergliiche.", "Foils auswählen, um Kennwerte zu vergleichen.", "Select foils to compare characteristics.", "Sélectionnez des foils pour comparer les caractéristiques.", "Seleziona i foil per confrontare le caratteristiche.", "Selecciona foils para comparar características."),
        "calc.chord": r("Chord", "Chord", "Chord", "Chord", "Corde", "Corda", "Cuerda"),
        "calc.stall": r("Stall", "Stall", "Stall", "Stall", "Décrochage", "Stallo", "Pérdida"),
        "calc.minViable": r("Min", "Min", "Min", "Min", "Min", "Min", "Mín"),
        "calc.optimal": r("Optimal", "Optimal", "Optimal", "Optimal", "Optimal", "Ottimale", "Óptima"),
        "calc.powerRow": r("Pump-Leistung (W) je km/h", "Pump-Leischtig (W) pro km/h", "Pump-Leistung (W) je km/h", "Pump power (W) per km/h", "Puissance de pump (W) par km/h", "Potenza di pump (W) per km/h", "Potencia de pump (W) por km/h"),
        "calc.disclaimer": r("Theoretisches Modell — Richtwerte, keine Garantie. Geschätzte Dicken sind markiert.", "Theoretischs Modäll — Richtwärt, kei Garantie. Gschätzti Dicke sind markiert.", "Theoretisches Modell — Richtwerte, keine Garantie. Geschätzte Dicken sind markiert.", "Theoretical model — guideline values, no guarantee. Estimated thicknesses are marked.", "Modèle théorique — valeurs indicatives, sans garantie. Les épaisseurs estimées sont marquées.", "Modello teorico — valori indicativi, nessuna garanzia. Gli spessori stimati sono contrassegnati.", "Modelo teórico — valores orientativos, sin garantía. Los grosores estimados están marcados."),
    ]

}
